// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "VarlockEnclave",
    platforms: [
        .macOS(.v13),
    ],
    targets: [
        // Legacy SecKeychain ACL wrappers — deprecated APIs with no replacement.
        // Isolated in a separate target so we can suppress deprecation warnings
        // without affecting the rest of the codebase.
        .target(
            name: "KeychainLegacy",
            path: "Sources/KeychainLegacy",
            swiftSettings: [
                .unsafeFlags(["-suppress-warnings"]),
            ],
            linkerSettings: [
                .linkedFramework("Security"),
            ]
        ),
        // Pure session-scoping logic (TTY / process-tree identity), isolated in
        // its own library target so it can be unit tested with synthetic process
        // trees. All OS access goes through the `ProcessProvider` abstraction.
        .target(
            name: "SessionScoping",
            path: "Sources/SessionScoping"
        ),
        // Identity-session logic: the varlock ECIES wire format against any P-256
        // key (software or enclave), and the grant table behind unlock sessions.
        // Kept out of the executable so both can be unit tested, including the
        // cross-implementation compat vector generated by the TypeScript side.
        .target(
            name: "IdentitySessions",
            path: "Sources/IdentitySessions"
        ),
        .executableTarget(
            name: "VarlockEnclave",
            dependencies: ["KeychainLegacy", "SessionScoping", "IdentitySessions"],
            path: "Sources/VarlockEnclave",
            linkerSettings: [
                .linkedFramework("Security"),
                .linkedFramework("LocalAuthentication"),
                .linkedFramework("AppKit"),
            ]
        ),
        .testTarget(
            name: "SessionScopingTests",
            dependencies: ["SessionScoping"],
            path: "Tests/SessionScopingTests"
        ),
        .testTarget(
            name: "IdentitySessionsTests",
            dependencies: ["IdentitySessions"],
            path: "Tests/IdentitySessionsTests",
            resources: [.copy("fixtures")]
        ),
    ]
)
