;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Literal token nodes.
(ws) @comment
(divider) @comment
(glued_hash_text) @string
(hash) @comment
(export) @keyword
(assign_key) @constructor
(function_name) @variable
(ident) @variable
(dec_name) @variable
(number) @number
(bool) @constant.builtin
(undefined) @constant.builtin
(triple_double) @string
(triple_tick) @string
(dq_string) @string
(sq_string) @string
(bt_string) @string
(quote_chunk) @string
(expansion) @variable
(slash_text) @string
(unquoted_text) @string
(dec_value_text) @string
(dec_arg_text) @string
(dec_text) @string
(dq_string_chars) @string
(dq_string_interpolation_1 "${") @punctuation.special
(dq_string_interpolation_1 "}") @punctuation.special
(dq_string_interpolation_2 "$(") @punctuation.special
(dq_string_interpolation_2 ")") @punctuation.special
(bt_string_chars) @string
(bt_string_interpolation_1 "${") @punctuation.special
(bt_string_interpolation_1 "}") @punctuation.special
(bt_string_interpolation_2 "$(") @punctuation.special
(bt_string_interpolation_2 ")") @punctuation.special

;; Keyword, operator, and punctuation literals.
"=" @operator
[
  "," "(" ")" "{" "}" "[" "]"
] @punctuation.delimiter

;; Contextual token scopes (grammar.contextualScopes).
(function_arg_key_value (assign_key) @attribute)
(object_literal_entry (assign_key) @attribute)
(decorator_arg_key (assign_key) @attribute)
