packages:
  - packages/**/*
  - '!packages/**/test/*'
  - examples/**/*

catalog:
  '@sindresorhus/is': ^7.1.1
  '@types/debug': ^4.1.12
  '@types/node': 25.0.3
  ansis: ^4.2.0
  debug: ^4.4.3
  outdent: ^0.8.0
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^7.1.12
  vitest: ^4.0.6

overrides:
  form-data: 4.0.4
  punycode: npm:punycode@^2.3.1