---
packages:
  - 'packages/**/*'

catalog:
  "ansis": "^4.1.0"
  "debug": "^4.3.4"
  "outdent": "^0.8.0"
  "tsup": "^8.2.4"
  "typescript": "^5.8.2"
  "vite": "^6.3.5"
  "vite-node": "^3.2.4"
  "vitest": "^3.2.4"
  "@sindresorhus/is": "^7.0.1"
  "@types/debug": "^4.1.12"
  "@types/node": "^24.1.0"
  
