packages:
  - packages/**/*
  - '!packages/**/test/*'
  - smoke-tests/*

catalog:
  '@sindresorhus/is': ^7.2.0
  '@types/node': 25.2.3
  ansis: ^4.2.0
  ky: ^1.14.3
  outdent: ^0.8.0
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18

overrides:
  form-data: 4.0.5
  # this removes a deprecation warning in GCP plugin
  punycode: npm:punycode@^2.3.1