packages:
  - packages/**/*
  - '!packages/**/test/*'
  - examples/**/*

catalog:
  '@sindresorhus/is': ^7.1.1
  '@types/debug': ^4.1.12
  '@types/node': 24.9.2
  ansis: ^4.2.0
  debug: ^4.4.3
  outdent: ^0.8.0
  tsup: ^8.5.0
  typescript: ^5.9.3
  vite: ^7.1.12
  vite-node: ^3.2.4
  vitest: ^4.0.6
