// Generated by scripts/sync-bundled-icons.ts (repo root) - do not edit by hand.
// Icons embedded in generated types without a network request. Viewable copies are in
// ./bundled-icons/, license notices in BUNDLED_ICONS_LICENSES.md
/* eslint-disable */
export const BUNDLED_ICONS: Record<string, string> = {
  "simple-icons:vault": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"m0 0l11.955 24L24 0zm13.366 4.827h1.393v1.38h-1.393zm-2.77 5.569H9.22V8.993h1.389zm0-2.087H9.22V6.906h1.389zm0-2.086H9.22V4.819h1.389zm2.087 6.263h-1.377V11.08h1.388zm0-2.09h-1.377V8.993h1.388zm0-2.087h-1.377V6.906h1.388zm0-2.086h-1.377V4.819h1.388zm.683.683h1.393v1.389h-1.393zm0 3.475V8.993h1.389v1.388Z\"/></svg>"
};
