# Labeler configuration

## core packages
varlock:
- changed-files:
  - any-glob-to-any-file: 'packages/varlock/*'
  - any-glob-to-any-file: 'packages/env-graph/*'
parser:
- changed-files:
  - any-glob-to-any-file: 'packages/env-spec-parser/*'
vscode-plugin:
- changed-files:
  - any-glob-to-any-file: 'packages/vscode-plugin/*'
nextjs-integration:
- changed-files:
  - any-glob-to-any-file: 'packages/integrations/nextjs/*'
vite-integration:
- changed-files:
  - any-glob-to-any-file: 'packages/integrations/vite/*'

## website + docs
docs:
- changed-files:
  - any-glob-to-any-file: 'packages/varlock-website/*'
