import { existsSync } from 'node:fs';
import path from 'node:path';
import {
  addTemplate, addServerPlugin, addTypeTemplate, addVitePlugin, defineNuxtModule,
} from '@nuxt/kit';
import type { NuxtModule } from '@nuxt/schema';
import {
  buildVarlockSsrInitCode, getVarlockEnvSourcePaths, varlockVitePlugin, type VarlockVitePluginOptions,
} from '@varlock/vite-integration';

export interface VarlockNuxtModuleOptions extends VarlockVitePluginOptions {
  /**
   * path (relative to the project root) of the types file generated by
   * `@generateTypes` in your `.env.schema`. Only needed for custom paths -
   * `shared/env.d.ts` and `env.d.ts` are detected automatically.
   */
  envTypesPath?: string,
}

const varlockNuxtModule: NuxtModule<VarlockNuxtModuleOptions> = defineNuxtModule<VarlockNuxtModuleOptions>({
  meta: {
    name: 'varlock',
    configKey: 'varlock',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },
  defaults: {},
  setup(moduleOptions, nuxt) {
    addVitePlugin(() => varlockVitePlugin({
      integrationTelemetry: {
        name: __VARLOCK_INTEGRATION_NAME__,
        version: __VARLOCK_INTEGRATION_VERSION__,
      },
      // Nuxt points vite's `root` at the srcDir (`app/` by default in Nuxt 4),
      // but `.env.schema` and `.env` files live at the project root. Without
      // this the plugin reloads varlock from the srcDir, finds no schema, and
      // silently drops every build-time `ENV.*` replacement.
      rootDir: nuxt.options.rootDir,
      ...moduleOptions,
    }));

    // Nitro builds the production server with its own rollup pass, so the init
    // module injected into vite's SSR entry never reaches `.output/server` —
    // and server routes (`server/api/**`) are never part of the vite SSR graph
    // at all. Register the same init sequence as a Nitro plugin so `ENV` is
    // initialized and the console/response patches (log redaction and leak
    // prevention) are installed before any request is handled.
    // Restart the dev server when any loaded env file changes. Nuxt's own
    // watcher only restarts on its dotenv file (`.env` by default) - edits to
    // `.env.schema` or other varlock-loaded files would otherwise leave the
    // nitro side (server routes, init plugin) running with stale env until a
    // manual restart. Nuxt watches absolute `options.watch` entries even when
    // they live outside `srcDir`.
    if (nuxt.options.dev) {
      for (const envFilePath of getVarlockEnvSourcePaths(nuxt.options.rootDir)) {
        if (!nuxt.options.watch.includes(envFilePath)) nuxt.options.watch.push(envFilePath);
      }
    }

    // Register the `@generateTypes` output with Nuxt's generated tsconfigs.
    // Nuxt 4 splits type contexts (app/server/shared/node) and none of them
    // include a root-level `env.d.ts`, so the `varlock/env` module
    // augmentation is invisible to app and server code without this.
    const envTypesCandidates = moduleOptions.envTypesPath
      ? [moduleOptions.envTypesPath]
      : ['shared/env.d.ts', 'env.d.ts'];
    const envTypesAbsPath = envTypesCandidates
      .map((p) => path.resolve(nuxt.options.rootDir, p))
      .find((p) => existsSync(p));
    if (envTypesAbsPath) {
      addTypeTemplate({
        filename: 'types/varlock-env.d.ts',
        getContents: () => `/// <reference path=${JSON.stringify(envTypesAbsPath)} />\n`,
      }, {
        nuxt: true, nitro: true, shared: true, node: true,
      });
    }

    const initTemplate = addTemplate({
      filename: 'varlock-nitro-init.mjs',
      write: true,
      getContents: () => [
        buildVarlockSsrInitCode({
          ...moduleOptions,
          // this runs before the vite plugin's `config` hook, so the plugin has
          // not corrected the load directory yet — `nuxt build --cwd ./app`
          // would otherwise bake an empty env into a `resolved-env` build
          rootDir: nuxt.options.rootDir,
          isDev: nuxt.options.dev,
          preserveSideEffectImports: true,
        }),
        // Nitro plugins must default-export a function. The init above runs as
        // a module side effect, which happens on import — earlier than the
        // plugin call, and earlier than any lazily-imported route handler.
        'export default () => {};',
      ].join('\n'),
    });
    addServerPlugin(initTemplate.dst);
  },
});

export default varlockNuxtModule;
