import { existsSync } from 'node:fs';
import path from 'node:path';
import {
  addPluginTemplate, addServerHandler, addServerPlugin, addTemplate, addTypeTemplate, addVitePlugin, defineNuxtModule,
} from '@nuxt/kit';
import type { NuxtModule } from '@nuxt/schema';
import {
  buildVarlockSsrInitCode, getVarlockEnvSourcePaths, getVarlockLoadedEnv, refreshVarlockEnv,
  varlockVitePlugin, type VarlockVitePluginOptions,
} from '@varlock/vite-integration';

const DEFAULT_PUBLIC_DYNAMIC_ENDPOINT = '/__varlock/public-env';

export interface VarlockNuxtModuleOptions extends VarlockVitePluginOptions {
  /**
   * path (relative to the project root) of the types file generated by
   * `@generateTypes` in your `.env.schema`. Only needed for custom paths -
   * `shared/env.d.ts` and `env.d.ts` are detected automatically.
   */
  envTypesPath?: string,
  /**
   * Inject a server route that returns `getPublicDynamicEnv()`, so browser
   * code can hydrate public+dynamic values via `loadPublicDynamicEnv()`.
   * - `undefined`: auto (enabled only when public+dynamic config exists)
   * - `true`: always enabled at the default path
   * - `false`: disabled
   * - object: enabled with a custom `path`
   */
  publicDynamicEndpoint?: boolean | { path?: string },
}

const varlockNuxtModule: NuxtModule<VarlockNuxtModuleOptions> = defineNuxtModule<VarlockNuxtModuleOptions>({
  meta: {
    name: 'varlock',
    configKey: 'varlock',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },
  defaults: {},
  setup(moduleOptions, nuxt) {
    addVitePlugin(() => varlockVitePlugin({
      integrationTelemetry: {
        name: __VARLOCK_INTEGRATION_NAME__,
        version: __VARLOCK_INTEGRATION_VERSION__,
      },
      // Nuxt points vite's `root` at the srcDir (`app/` by default in Nuxt 4),
      // but `.env.schema` and `.env` files live at the project root. Without
      // this the plugin reloads varlock from the srcDir, finds no schema, and
      // silently drops every build-time `ENV.*` replacement.
      rootDir: nuxt.options.rootDir,
      ...moduleOptions,
    }));

    // Nitro builds the production server with its own rollup pass, so the init
    // module injected into vite's SSR entry never reaches `.output/server` —
    // and server routes (`server/api/**`) are never part of the vite SSR graph
    // at all. Register the same init sequence as a Nitro plugin so `ENV` is
    // initialized and the console/response patches (log redaction and leak
    // prevention) are installed before any request is handled.
    // Restart the dev server when any loaded env file changes. Nuxt's own
    // watcher only restarts on its dotenv file (`.env` by default) - edits to
    // `.env.schema` or other varlock-loaded files would otherwise leave the
    // nitro side (server routes, init plugin) running with stale env until a
    // manual restart. Nuxt watches absolute `options.watch` entries even when
    // they live outside `srcDir`.
    if (nuxt.options.dev) {
      // `watch` is missing from the resolved options on some older nuxt 3
      // versions - pushing into a fresh array is then a harmless no-op
      nuxt.options.watch ||= [];
      for (const envFilePath of getVarlockEnvSourcePaths(nuxt.options.rootDir)) {
        if (!nuxt.options.watch.includes(envFilePath)) nuxt.options.watch.push(envFilePath);
      }
      // Re-resolve env when a dev reload begins, BEFORE the new nuxt instance
      // evaluates nuxt.config. `ENV` is a proxy over shared global state, so
      // refreshing the store here makes config-time reads (`varlock/auto-load`
      // in nuxt.config) and re-injected process.env values fresh, even though
      // the config's cached auto-load import does not re-execute.
      //
      // Two hooks because reloads reach a running instance two ways: env-file
      // changes surfaced via `options.watch` invoke the `restart` hook, while
      // the CLI's own config watcher (nuxt.config edits, its dotenv file) can
      // reload directly without it - but every reload path closes the old
      // instance first, so `close` catches those. Deduped since a hook-driven
      // restart fires both.
      let lastEnvRefreshAt = 0;
      const refreshEnvOnce = () => {
        if (Date.now() - lastEnvRefreshAt < 1000) return;
        lastEnvRefreshAt = Date.now();
        refreshVarlockEnv(nuxt.options.rootDir);
      };
      nuxt.hook('restart', refreshEnvOnce);
      nuxt.hook('close', refreshEnvOnce);
    }

    // Inject a nitro route serving public+dynamic values to the browser, same
    // as the Astro integration's `/__varlock/public-env` route. Auto mode only
    // injects when the schema actually declares public+dynamic items. The
    // handler runs after the nitro init plugin (registered below), so ENV is
    // initialized by the time a request hits it.
    const pdOption = moduleOptions.publicDynamicEndpoint;
    let injectPublicDynamicEndpoint = pdOption === true || typeof pdOption === 'object';
    if (pdOption === undefined) {
      const loadedEnv = getVarlockLoadedEnv(nuxt.options.rootDir);
      injectPublicDynamicEndpoint = Object.values(loadedEnv?.config || {}).some(
        (itemInfo) => (itemInfo.isDynamic ?? itemInfo.isSensitive) && !itemInfo.isSensitive,
      );
    }
    if (injectPublicDynamicEndpoint) {
      const routePath = (typeof pdOption === 'object' && pdOption.path) || DEFAULT_PUBLIC_DYNAMIC_ENDPOINT;
      if (!routePath.startsWith('/')) {
        throw new Error('[varlock] `publicDynamicEndpoint.path` must start with "/"');
      }
      const endpointTemplate = addTemplate({
        filename: 'varlock-public-env-handler.mjs',
        write: true,
        getContents: () => [
          "import { defineEventHandler } from 'h3';",
          "import { getPublicDynamicEnv } from 'varlock/env';",
          'export default defineEventHandler(() => getPublicDynamicEnv());',
        ].join('\n'),
      });
      addServerHandler({ route: routePath, method: 'get', handler: endpointTemplate.dst });

      // `loadPublicDynamicEnv()` defaults to the standard path; for a custom
      // path, point the client runtime at it so callers don't have to pass
      // `endpoint` themselves
      if (routePath !== DEFAULT_PUBLIC_DYNAMIC_ENDPOINT) {
        addPluginTemplate({
          filename: 'varlock-public-env-endpoint.mjs',
          getContents: () => [
            "import { defineNuxtPlugin } from '#app';",
            'export default defineNuxtPlugin(() => {',
            `  globalThis.__varlockPublicDynamicEnvEndpoint = ${JSON.stringify(routePath)};`,
            '});',
          ].join('\n'),
        });
      }
    }

    // Register the `@generateTypes` output with Nuxt's generated tsconfigs.
    // Nuxt 4 splits type contexts (app/server/shared/node) and none of them
    // include a root-level `env.d.ts`, so the `varlock/env` module
    // augmentation is invisible to app and server code without this.
    const envTypesCandidates = moduleOptions.envTypesPath
      ? [moduleOptions.envTypesPath]
      : ['shared/env.d.ts', 'env.d.ts'];
    const envTypesAbsPath = envTypesCandidates
      .map((p) => path.resolve(nuxt.options.rootDir, p))
      .find((p) => existsSync(p));
    if (envTypesAbsPath) {
      addTypeTemplate({
        filename: 'types/varlock-env.d.ts',
        getContents: () => `/// <reference path=${JSON.stringify(envTypesAbsPath)} />\n`,
      }, {
        nuxt: true, nitro: true, shared: true, node: true,
      });
    }

    const initTemplate = addTemplate({
      filename: 'varlock-nitro-init.mjs',
      write: true,
      getContents: () => [
        buildVarlockSsrInitCode({
          ...moduleOptions,
          // this runs before the vite plugin's `config` hook, so the plugin has
          // not corrected the load directory yet — `nuxt build --cwd ./app`
          // would otherwise bake an empty env into a `resolved-env` build
          rootDir: nuxt.options.rootDir,
          isDev: nuxt.options.dev,
          preserveSideEffectImports: true,
        }),
        // Nitro plugins must default-export a function. The init above runs as
        // a module side effect, which happens on import — earlier than the
        // plugin call, and earlier than any lazily-imported route handler.
        'export default () => {};',
      ].join('\n'),
    });
    addServerPlugin(initTemplate.dst);
  },
});

export default varlockNuxtModule;
