/**
 * Generate the cross-implementation ECIES compat vector.
 *
 * The Swift daemon and the TypeScript library both implement the varlock ECIES
 * wire format. This writes a payload produced by the TS implementation so the
 * Swift tests can prove they read the same bytes. Regenerate only when the wire
 * format changes on purpose:
 *
 *   bun run packages/encryption-binary-swift/scripts/generate-ecies-fixture.ts
 *
 * A Swift-side failure against a fixture that was NOT regenerated means the two
 * implementations have drifted, which is the point of checking it in.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  createKeyPair, decrypt, encrypt,
  DEVICE_PAYLOAD_VERSION, IDENTITY_PAYLOAD_VERSION,
} from '../../varlock/src/lib/local-encrypt/crypto';

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(here, '../swift/Tests/IdentitySessionsTests/fixtures/ecies-vector.json');

const IDENTITY_PLAINTEXT = 'sk-varlock-compat-vector-🔐-multibyte';
const DEVICE_PLAINTEXT = 'device payload, same wire format, different version byte';

const identityKeyPair = await createKeyPair();
const deviceKeyPair = await createKeyPair();

const fixture = {
  note: 'Generated by packages/encryption-binary-swift/scripts/generate-ecies-fixture.ts. Do not hand-edit.',
  generatedBy: 'varlock TypeScript crypto.ts',
  hkdfSalt: 'varlock-ecies-v1',
  identity: {
    version: IDENTITY_PAYLOAD_VERSION,
    publicKey: identityKeyPair.publicKey,
    privateKeyPkcs8: identityKeyPair.privateKey,
    plaintext: IDENTITY_PLAINTEXT,
    payload: await encrypt(identityKeyPair.publicKey, IDENTITY_PLAINTEXT, { version: IDENTITY_PAYLOAD_VERSION }),
  },
  device: {
    version: DEVICE_PAYLOAD_VERSION,
    publicKey: deviceKeyPair.publicKey,
    privateKeyPkcs8: deviceKeyPair.privateKey,
    plaintext: DEVICE_PLAINTEXT,
    payload: await encrypt(deviceKeyPair.publicKey, DEVICE_PLAINTEXT, { version: DEVICE_PAYLOAD_VERSION }),
  },
};

// Sanity check the fixture round-trips in TS before asking Swift to read it
for (const entry of [fixture.identity, fixture.device]) {
  const roundTripped = await decrypt(entry.privateKeyPkcs8, entry.publicKey, entry.payload);
  if (roundTripped !== entry.plaintext) {
    throw new Error('fixture failed to round-trip through the TS implementation');
  }
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`wrote ${outPath}`);
