/**
 * @file Tree-sitter grammar generated by monogram from a single CstGrammar.
 * @license MIT
 *
 * GENERATED — do not edit by hand. Regenerate from the source grammar.
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "env_spec",

  extras: $ => [
    /\s/,
    $.ws
  ],

  externals: $ => [
    $.dq_string_chars,
    $.bt_string_chars
  ],

  rules: {
    file: $ => repeat($.line),

    static_value_part: $ => choice($.triple_double, $.triple_tick, $.dq_string, $.sq_string, $.bt_string, $.quote_chunk, $.number, $.bool, $.undefined, $.expansion, $.slash_text, $.ident, "(", ")", $.unquoted_text),

    function_arg_value_part: $ => choice($.function_call, $.triple_double, $.triple_tick, $.dq_string, $.sq_string, $.bt_string, $.number, $.bool, $.undefined, $.expansion, $.slash_text, $.unquoted_text, $.ident, $.arg_unquoted_text, $.hash),

    function_arg_value: $ => repeat1($.function_arg_value_part),

    function_arg_key_value: $ => seq($.assign_key, "=", $.function_arg_value),

    function_arg: $ => choice($.function_arg_key_value, $.function_arg_value),

    function_args: $ => seq("(", optional(optional(seq($.function_arg, repeat(seq(",", $.function_arg)), optional(",")))), optional(","), ")"),

    function_call: $ => seq($.function_name, $.function_args),

    value: $ => choice($.function_call, repeat1($.static_value_part)),

    decorator_line_prefix: $ => $.hash,

    decorator_function_arg_value: $ => choice($.decorator_function_call, $.dq_string, $.sq_string, $.bt_string, $.dec_value_text, $.dec_text, $.dec_arg_text, $.slash_text, $.unquoted_text, $.expansion, $.ident, $.number, $.bool, $.undefined),

    decorator_arg_key: $ => choice($.assign_key, $.ident),

    decorator_function_arg_key_value: $ => seq($.decorator_arg_key, "=", $.decorator_function_arg_value),

    decorator_function_arg: $ => choice($.decorator_function_arg_key_value, $.decorator_function_arg_value),

    decorator_function_arg_chunk: $ => seq(optional($.decorator_line_prefix), $.decorator_function_arg),

    decorator_function_args: $ => seq("(", optional(optional(seq($.decorator_function_arg_chunk, repeat(seq(",", $.decorator_function_arg_chunk)), optional(",")))), optional(","), optional($.decorator_line_prefix), ")"),

    decorator_function_call: $ => seq($.function_name, $.decorator_function_args),

    decorator_value: $ => choice($.decorator_function_call, $.dq_string, $.sq_string, $.bt_string, $.slash_text, $.unquoted_text, $.expansion, $.ident, $.number, $.bool, $.undefined, $.dec_value_text),

    decorator_assigned_value: $ => seq("=", $.decorator_value),

    decorator: $ => seq($.dec_name, optional(choice($.decorator_function_args, $.decorator_assigned_value))),

    decorator_text: $ => choice($.ident, $.assign_key, $.number, $.bool, $.undefined, $.dq_string, $.sq_string, $.bt_string, $.unquoted_text, $.expansion, $.dec_value_text, $.dec_text, "=", ",", "(", ")"),

    decorator_or_text: $ => choice($.decorator, $.decorator_text),

    post_comment_part: $ => choice($.dec_name, $.dec_text, $.dec_value_text, $.assign_key, $.ident, $.number, $.bool, $.undefined, $.dq_string, $.sq_string, $.bt_string, $.unquoted_text, $.expansion, "=", ",", "(", ")"),

    post_comment: $ => seq($.hash, repeat($.post_comment_part)),

    trailing_comment: $ => seq($.hash, repeat($.post_comment_part)),

    decorator_post_comment: $ => choice($.post_comment, $.trailing_comment),

    decorator_comment: $ => seq($.decorator, repeat($.decorator_or_text), optional($.decorator_post_comment)),

    decorator_comment_line: $ => seq($.hash, $.decorator_comment),

    inline_decorator_comment: $ => seq($.hash, $.decorator_comment),

    statement: $ => choice($.divider, $.decorator_comment_line, $.trailing_comment, seq(optional($.export), $.assign_key, "=", optional($.value), optional(choice($.inline_decorator_comment, $.post_comment, $.trailing_comment)))),

    line: $ => choice(seq(repeat(choice($.indent, $.dedent)), $.statement, optional($.newline)), seq(repeat1(choice($.indent, $.dedent)), optional($.newline)), $.newline),

    ws: $ => token(/[ \t]+/),

    indent: $ => token(//),

    dedent: $ => token(//),

    newline: $ => token(//),

    divider: $ => token(/#[ \t]*[-=~#]{3,}[^\r\n]*/),

    hash: $ => token(/#/),

    export: $ => token(/export\b/),

    assign_key: $ => token(/[a-zA-Z_][a-zA-Z0-9._-]*/),

    function_name: $ => token(/[a-zA-Z][a-zA-Z0-9_]*/),

    ident: $ => token(/[a-zA-Z_][a-zA-Z0-9._-]*/),

    dec_name: $ => token(/@[a-zA-Z][^ \t\n=()#@]*/),

    number: $ => token(/-?(?:\d+\.\d+|\d+)/),

    bool: $ => token(/(?:true|false)\b/),

    undefined: $ => token(/undefined\b/),

    triple_double: $ => token(/"""[\s\S]*?\n[\s\S]*?"""/),

    triple_tick: $ => token(/```(?:\\```|[\s\S])*?```/),

    sq_string: $ => token(/'(?:\\.|[^'\\])*'/),

    quote_chunk: $ => token(/["'`]+/),

    expansion: $ => token(/(?:\\?\$\{?[a-zA-Z_][a-zA-Z0-9_]*\}?|\\?\$\([^)]+\))/),

    slash_text: $ => token(/\/[^#=,\r\n()]*/),

    unquoted_text: $ => token(/[^#=,\r\n()$"'`\t ][^#=,\r\n()$]*/),

    arg_unquoted_text: $ => token(/[^ \t\n,()=#][^ \t\n,)]*/),

    dec_value_text: $ => token(/[^# \t\n=(),"'`$][^# \t\n=(),$]*/),

    dec_arg_text: $ => token(/[^ \t\n,()#="'`$][^ \t\n,()#=$]*/),

    dec_text: $ => token(/[^@#=\s(),"'`$][^@#=\s(),"'`$]*/),

    dq_string: $ => seq(
      "\"",
      repeat(choice($.dq_string_chars, $.dq_string_interpolation_1, $.dq_string_interpolation_2)),
      "\""
    ),

    dq_string_interpolation_1: $ => seq("${", blank(), "}"),

    dq_string_interpolation_2: $ => seq("$(", blank(), ")"),

    bt_string: $ => seq(
      "`",
      repeat(choice($.bt_string_chars, $.bt_string_interpolation_1, $.bt_string_interpolation_2)),
      "`"
    ),

    bt_string_interpolation_1: $ => seq("${", blank(), "}"),

    bt_string_interpolation_2: $ => seq("$(", blank(), ")")
  }
});

// entry rule: file
