// Tree-sitter external scanner generated by monogram (indentation path).
//
// Mirrors the indent-stack state machine of src/gen-lexer.ts: INDENT / DEDENT / NEWLINE are emitted
// from the line-leading column relative to an indent stack; a block-scalar body is scanned verbatim.
// All language data (comment introducer, block-scalar introducers, document markers) is DERIVED from
// the grammar's `indent` config — nothing below is hand-tuned for a specific language.

#include "tree_sitter/parser.h"
#include "tree_sitter/alloc.h"
#include <string.h>
#include <stdint.h>

enum TokenType {
  INDENT,
  DEDENT,
  NEWLINE,
  DQ_STRING_CHARS,
  BT_STRING_CHARS,
};

typedef struct {
  uint32_t len;          // indent-stack depth (>= 1; stack[0] == 0, the document level)
  uint32_t cap;
  int16_t *stack;        // indentation columns
  int16_t pending_col;   // column of the line boundary mid-processing (-1 = none)
  bool pending_newline;  // a NEWLINE is still owed once dedents reach pending_col
  bool started;          // any content lexed yet (suppresses a leading NEWLINE)
} Scanner;

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

static void push_indent(Scanner *s, int16_t col) {
  if (s->len == s->cap) { s->cap *= 2; s->stack = ts_realloc(s->stack, s->cap * sizeof(int16_t)); }
  s->stack[s->len++] = col;
}

void *tree_sitter_env_spec_external_scanner_create(void) {
  Scanner *s = ts_malloc(sizeof(Scanner));
  s->cap = 16; s->len = 1;
  s->stack = ts_malloc(s->cap * sizeof(int16_t));
  s->stack[0] = 0;
  s->pending_col = -1; s->pending_newline = false; s->started = false;
  return s;
}

void tree_sitter_env_spec_external_scanner_destroy(void *payload) {
  Scanner *s = (Scanner *)payload;
  ts_free(s->stack);
  ts_free(s);
}

unsigned tree_sitter_env_spec_external_scanner_serialize(void *payload, char *buffer) {
  Scanner *s = (Scanner *)payload;
  unsigned n = 0;
  buffer[n++] = s->started ? 1 : 0;
  buffer[n++] = s->pending_newline ? 1 : 0;
  memcpy(&buffer[n], &s->pending_col, sizeof(int16_t)); n += sizeof(int16_t);
  uint32_t count = s->len;
  while (n + sizeof(uint32_t) + count * sizeof(int16_t) > TREE_SITTER_SERIALIZATION_BUFFER_SIZE && count > 0) count--;
  memcpy(&buffer[n], &count, sizeof(uint32_t)); n += sizeof(uint32_t);
  memcpy(&buffer[n], s->stack, count * sizeof(int16_t)); n += count * sizeof(int16_t);
  return n;
}

void tree_sitter_env_spec_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  Scanner *s = (Scanner *)payload;
  s->len = 1; s->stack[0] = 0; s->pending_col = -1; s->pending_newline = false; s->started = false;
  if (length < 2 + sizeof(int16_t) + sizeof(uint32_t)) return;
  unsigned n = 0;
  s->started = buffer[n++] != 0;
  s->pending_newline = buffer[n++] != 0;
  memcpy(&s->pending_col, &buffer[n], sizeof(int16_t)); n += sizeof(int16_t);
  uint32_t count; memcpy(&count, &buffer[n], sizeof(uint32_t)); n += sizeof(uint32_t);
  if (count == 0) return; // keep stack[0] = 0
  while (s->cap < count) { s->cap *= 2; s->stack = ts_realloc(s->stack, s->cap * sizeof(int16_t)); }
  memcpy(s->stack, &buffer[n], count * sizeof(int16_t));
  s->len = count;
}


bool tree_sitter_env_spec_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid_symbols) {
  Scanner *s = (Scanner *)payload;
  bool want_indent = valid_symbols[INDENT];
  bool want_dedent = valid_symbols[DEDENT];
  bool want_newline = valid_symbols[NEWLINE];

  // Finish a line boundary already in progress: emit the remaining DEDENTs (one per call), then the
  // owed NEWLINE when the stack top reaches the boundary column. No input is consumed here.
  if (s->pending_col >= 0) {
    int top = s->stack[s->len - 1];
    if (s->pending_col < top) {
      if (want_dedent) { s->len--; lexer->result_symbol = DEDENT; return true; }
      s->pending_col = -1; s->pending_newline = false; return false;
    }
    bool owed = s->pending_newline;
    int16_t col = s->pending_col;
    s->pending_col = -1; s->pending_newline = false;
    if (col == top && owed && want_newline && s->started) { lexer->result_symbol = NEWLINE; return true; }
    return false;
  }

  if (!want_indent && !want_dedent && !want_newline) return false; // no indent tokens valid

  // Skip blank lines, comment-only lines, and leading whitespace, noting whether a line break was
  // crossed (only a real boundary drives the indent logic).
  bool found_eol = false;
  for (;;) {
    int32_t c = lexer->lookahead;
    if (c == '\n') { skip(lexer); found_eol = true; }
    else if (c == '\r') { skip(lexer); if (lexer->lookahead == '\n') skip(lexer); found_eol = true; }
    else if (c == ' ' || c == '\t') { skip(lexer); }
    else if (c == '#') { while (lexer->lookahead != 0 && lexer->lookahead != '\n' && lexer->lookahead != '\r') skip(lexer); }
    else break; // content or EOF
  }

  if (lexer->eof(lexer)) {
    if (s->len > 1 && want_dedent) { s->len--; lexer->result_symbol = DEDENT; return true; } // close open blocks at EOF
    return false;
  }
  bool was_started = s->started;
  s->started = true; // content lies ahead — mark started even on a mid-line return
  if (!found_eol) return false; // not at a line boundary

  int16_t col = (int16_t)lexer->get_column(lexer);
  lexer->mark_end(lexer); // INDENT/DEDENT/NEWLINE are zero-width at the content column
  int top = s->stack[s->len - 1];

  if (col > top) {
    if (want_indent) { push_indent(s, col); lexer->result_symbol = INDENT; return true; }
    return false;
  }
  if (col == top) {
    if (want_newline && was_started) { lexer->result_symbol = NEWLINE; return true; }
    return false;
  }
  // col < top: a dedent. Emit one DEDENT now; queue the rest + the trailing NEWLINE for re-entry.
  if (want_dedent) {
    s->pending_col = col; s->pending_newline = true;
    s->len--; lexer->result_symbol = DEDENT; return true;
  }
  return false;
}
