// Tree-sitter external scanner generated by monogram.
//
// COMPLETE — the regex-literal scan and interpolated-span scans are wired
// from grammar token hints (`regexContext`, `template`, `interpolation`).
//
// All language-specific data below is DERIVED from the CstGrammar, not
// hardcoded: regex flags and interpolation delimiters come from token hints.

#include "tree_sitter/parser.h"
#include "tree_sitter/alloc.h"
#include <string.h>
#include <wctype.h>

enum TokenType {
  DQ_STRING_CHARS,
  BT_STRING_CHARS,
};

// The scanner is stateless — tree-sitter's `valid_symbols` already encodes
// the parse context (inside a regex slot? inside a template span?), and the
// `${ … }` / `$( … )` nesting is handled by substitution rules in the
// CFG, so there is nothing to (de)serialize.
typedef struct { char unused; } Scanner;

void *tree_sitter_env_spec_external_scanner_create(void) {
  return ts_calloc(1, sizeof(Scanner));
}

void tree_sitter_env_spec_external_scanner_destroy(void *payload) {
  ts_free(payload);
}

unsigned tree_sitter_env_spec_external_scanner_serialize(void *payload, char *buffer) {
  (void)payload; (void)buffer;
  return 0;
}

void tree_sitter_env_spec_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  (void)payload; (void)buffer; (void)length;
}

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

// ── Interpolated-span scan ─────────────────────────────────────
// Scans literal chars inside one interpolated token span. Stops
// before the closing delimiter or before any interpolation opener,
// so holes re-enter the expression grammar.
//
// token       = DQ_STRING
// open        = "\""
// openers     = "${", "$("
static bool scan_dq_string_chars(TSLexer *lexer) {
  const char open = '"';
  bool has_content = false;
  for (;;) {
    lexer->mark_end(lexer);
    int32_t c = lexer->lookahead;
    if (c == 0) return false; // EOF — let the CFG report an unterminated span
    if (c == open) break;
    if (c == '$') {
      advance(lexer); // peek second opener char
      if (lexer->lookahead == '{' || lexer->lookahead == '(') break;
      has_content = true;
      continue;
    }
    // Backslash escape: consume `\` + next so an escaped delimiter stays literal.
    if (c == '\\') {
      advance(lexer);
      if (lexer->lookahead != 0) advance(lexer);
      has_content = true;
      continue;
    }
    advance(lexer);
    has_content = true;
  }
  if (!has_content) return false;
  lexer->result_symbol = DQ_STRING_CHARS;
  return true;
}

// ── Interpolated-span scan ─────────────────────────────────────
// Scans literal chars inside one interpolated token span. Stops
// before the closing delimiter or before any interpolation opener,
// so holes re-enter the expression grammar.
//
// token       = BT_STRING
// open        = "`"
// openers     = "${", "$("
static bool scan_bt_string_chars(TSLexer *lexer) {
  const char open = '`';
  bool has_content = false;
  for (;;) {
    lexer->mark_end(lexer);
    int32_t c = lexer->lookahead;
    if (c == 0) return false; // EOF — let the CFG report an unterminated span
    if (c == open) break;
    if (c == '$') {
      advance(lexer); // peek second opener char
      if (lexer->lookahead == '{' || lexer->lookahead == '(') break;
      has_content = true;
      continue;
    }
    // Backslash escape: consume `\` + next so an escaped delimiter stays literal.
    if (c == '\\') {
      advance(lexer);
      if (lexer->lookahead != 0) advance(lexer);
      has_content = true;
      continue;
    }
    advance(lexer);
    has_content = true;
  }
  if (!has_content) return false;
  lexer->result_symbol = BT_STRING_CHARS;
  return true;
}

bool tree_sitter_env_spec_external_scanner_scan(void *payload, TSLexer *lexer,
                                                          const bool *valid_symbols) {
  (void)payload;

  // Interpolated-span chars run first: whitespace INSIDE a span is literal
  // text, so it must NOT be skipped (unlike the regex path below).
  if (valid_symbols[DQ_STRING_CHARS]) {
    if (scan_dq_string_chars(lexer)) return true;
  }
  if (valid_symbols[BT_STRING_CHARS]) {
    if (scan_bt_string_chars(lexer)) return true;
  }

  return false;
}
