/* eslint-disable no-console */

import fs from 'node:fs';
import path from 'node:path';
import type { SerializedEnvGraph } from 'varlock';

type LoaderContext = {
  cacheable(flag: boolean): void;
  resourcePath: string;
  rootContext: string;
};

function escapeRegExp(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// matches: import { ENV } from 'varlock/env'  (with various quote styles and spacing)
const VARLOCK_ENV_IMPORT_RE = /import\s*\{\s*ENV\s*\}\s*from\s*['"]varlock\/env['"]\s*;?/;

// detect 'use client' directive at top of file (before any code, after optional comments)
const USE_CLIENT_RE = /^(?:\s*\/\/[^\n]*\n|\s*\/\*[\s\S]*?\*\/\s*\n)*\s*['"]use client['"]/;

// match directive prologue ('use server', 'use client', etc.) + optional trailing semicolons/newlines
// captures the directive block so we can inject code after it
const DIRECTIVE_PROLOGUE_RE = /^((?:\s*\/\/[^\n]*\n|\s*\/\*[\s\S]*?\*\/\s*\n)*\s*['"]use (?:server|client|strict)['"]\s*;?\s*\n?)/;

/** Prepend code after any directive prologue (e.g. 'use server') to avoid breaking it */
function prependAfterDirectives(source: string, codeToPrepend: string): string {
  const match = source.match(DIRECTIVE_PROLOGUE_RE);
  if (match) {
    return match[1] + codeToPrepend + '\n' + source.slice(match[1].length);
  }
  return codeToPrepend + '\n' + source;
}

// load the pre-bundled varlock/env CJS module at loader load time
// this file is generated by tsup (second config entry with noExternal)
let varlockEnvInlineCode: string | undefined;
const inlinePath = path.resolve(__dirname, './varlock-env-inline.js');
try {
  const rawCjs = fs.readFileSync(inlinePath, 'utf8');
  // wrap CJS bundle in an IIFE so `ENV` becomes a local binding when inlined
  varlockEnvInlineCode = [
    'var { ENV } = (function() {',
    '  var module = { exports: {} }; var exports = module.exports;',
    rawCjs,
    '  return module.exports;',
    '})();',
  ].join('\n');
  console.log(`[varlock-turbopack] loaded inline env bundle (${varlockEnvInlineCode.length} bytes) from ${inlinePath}`);
} catch (err) {
  console.warn(`[varlock-turbopack] could not load inline env bundle from ${inlinePath}:`, err);
}

/**
 * Turbopack-compatible webpack loader that:
 * 1. In instrumentation.ts/js: inlines __VARLOCK_ENV + self-contained env bundle
 *    (guaranteed server-only, runs once at startup — handles init + all patches)
 * 2. In proxy.ts/proxy.js: replaces `import { ENV } from 'varlock/env'` with inlined
 *    env bundle (Turbopack can't resolve varlock/env in the proxy/middleware context)
 * 3. Replaces `ENV.KEY` references for non-sensitive vars with literal JSON values
 *
 * SECURITY: Sensitive env values are ONLY embedded into files that are guaranteed
 * server-only (instrumentation.ts, proxy.ts). The static ENV.KEY replacements
 * explicitly skip sensitive vars.
 */
function turbopackLoader(this: LoaderContext, source: string) {
  // disable caching so we always re-run when env values change
  this.cacheable(false);

  // only transform files within the project root
  // this skips node_modules AND symlinked workspace packages (e.g. varlock/env)
  // which turbopack resolves to their real paths outside node_modules
  const projectRoot = this.rootContext || process.cwd();
  if (!this.resourcePath.startsWith(projectRoot)) {
    return source;
  }
  // still skip node_modules within the project root
  const relPath = this.resourcePath.slice(projectRoot.length);
  if (relPath.includes('/node_modules/') || relPath.includes('\\node_modules\\')) {
    return source;
  }

  console.log(`[varlock-turbopack] processing: ${relPath}`);

  // skip client components — patches use node builtins (zlib, http) that don't work in browser
  const isClientComponent = USE_CLIENT_RE.test(source);
  if (isClientComponent) {
    console.log(`[varlock-turbopack] skipping client component: ${relPath}`);
    return source;
  }

  const rawEnv = process.env.__VARLOCK_ENV;
  if (!rawEnv) {
    console.log(`[varlock-turbopack] no __VARLOCK_ENV, skipping: ${relPath}`);
    return source;
  }

  let envGraph: SerializedEnvGraph;
  try {
    envGraph = JSON.parse(rawEnv);
  } catch {
    return source;
  }

  let result = source;

  const hasVarlockImport = VARLOCK_ENV_IMPORT_RE.test(result);
  const isProxyFile = /[/\\]proxy\.[jt]sx?$/.test(this.resourcePath);
  const isInstrumentationFile = /[/\\]instrumentation\.[jt]sx?$/.test(this.resourcePath);
  console.log(`[varlock-turbopack] ${relPath}: hasVarlockImport=${hasVarlockImport}, isProxyFile=${isProxyFile}, isInstrumentation=${isInstrumentationFile}, hasInlineCode=${!!varlockEnvInlineCode}`);

  if (isInstrumentationFile) {
    // instrumentation.ts/js: runs once at server startup, guaranteed server-only.
    // Inline the resolved env data + self-contained bundle to init varlock
    // and apply all patches (console redaction, response scanning, leak prevention).
    // The baked-in __VARLOCK_ENV is used as a fallback — runtime env takes precedence.
    if (varlockEnvInlineCode) {
      const injectCode = [
        `process.env.__VARLOCK_ENV = process.env.__VARLOCK_ENV || ${JSON.stringify(rawEnv)};`,
        varlockEnvInlineCode,
      ].join('\n');
      result = prependAfterDirectives(result, injectCode);
      console.log(`[varlock-turbopack] ✅ injected varlock init (inline bundle) into instrumentation file: ${relPath}`);
    } else {
      console.warn('[varlock-turbopack] ⚠️ instrumentation file found but inline bundle not available!');
    }
  } else if (isProxyFile && hasVarlockImport) {
    if (varlockEnvInlineCode) {
      // proxy.ts/js: runs in an isolated middleware/edge context where Turbopack
      // can't resolve varlock/env. Inline the entire module + env data.
      // This is safe because proxy files are always server-only.
      const inlineCode = [
        `process.env.__VARLOCK_ENV = ${JSON.stringify(rawEnv)};`,
        varlockEnvInlineCode,
      ].join('\n');
      result = result.replace(VARLOCK_ENV_IMPORT_RE, inlineCode);
      console.log(`[varlock-turbopack] ✅ inlined varlock/env into ${relPath} (${inlineCode.length} bytes)`);
    } else {
      console.warn('[varlock-turbopack] ⚠️ proxy file has varlock/env import but inline bundle not available!');
    }
  }

  // static replacements for non-sensitive env vars
  if (source.includes('ENV.')) {
    for (const [key, item] of Object.entries(envGraph.config)) {
      if (item.isSensitive) continue;

      // match ENV.KEY as a member expression (word boundary before ENV, not followed by more identifier chars)
      const pattern = new RegExp(`\\bENV\\.${escapeRegExp(key)}(?![\\w$])`, 'g');
      result = result.replace(pattern, JSON.stringify(item.value));
    }
  }

  return result;
}

// CJS export required for webpack loader-runner compatibility
module.exports = turbopackLoader;
