/* eslint-disable no-console */

import fs from 'node:fs';
import path from 'node:path';
import type { SerializedEnvGraph } from 'varlock';

type LoaderContext = {
  cacheable(flag: boolean): void;
  resourcePath: string;
  rootContext: string;
};

function escapeRegExp(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// matches: import { ENV } from 'varlock/env'  (with various quote styles and spacing)
const VARLOCK_ENV_IMPORT_RE = /import\s*\{\s*ENV\s*\}\s*from\s*['"]varlock\/env['"]\s*;?/;

// load the pre-bundled varlock/env CJS module at loader load time
// this file is generated by tsup (second config entry with noExternal)
let varlockEnvInlineCode: string | undefined;
const inlinePath = path.resolve(__dirname, './varlock-env-inline.js');
try {
  const rawCjs = fs.readFileSync(inlinePath, 'utf8');
  // wrap CJS bundle in an IIFE so `ENV` becomes a local binding when inlined
  varlockEnvInlineCode = [
    'var { ENV } = (function() {',
    '  var module = { exports: {} }; var exports = module.exports;',
    rawCjs,
    '  return module.exports;',
    '})();',
  ].join('\n');
  console.log(`[varlock-turbopack] loaded inline env bundle (${varlockEnvInlineCode.length} bytes) from ${inlinePath}`);
} catch (err) {
  console.warn(`[varlock-turbopack] could not load inline env bundle from ${inlinePath}:`, err);
}

/**
 * Turbopack-compatible webpack loader that:
 * 1. In proxy.ts/proxy.js: replaces `import { ENV } from 'varlock/env'` with inlined
 *    env values (Turbopack can't resolve varlock/env in the proxy/middleware context)
 * 2. In other files importing varlock/env: prepends process.env.__VARLOCK_ENV assignment
 * 3. Replaces `ENV.KEY` references for non-sensitive vars with literal JSON values
 *
 * Reads from `process.env.__VARLOCK_ENV` which is set by next-env-compat.ts
 * before any bundler activity starts.
 */
function turbopackLoader(this: LoaderContext, source: string) {
  // disable caching so we always re-run when env values change
  this.cacheable(false);

  // only transform files within the project root
  // this skips node_modules AND symlinked workspace packages (e.g. varlock/env)
  // which turbopack resolves to their real paths outside node_modules
  const projectRoot = this.rootContext || process.cwd();
  if (!this.resourcePath.startsWith(projectRoot)) {
    return source;
  }
  // still skip node_modules within the project root
  const relPath = this.resourcePath.slice(projectRoot.length);
  if (relPath.includes('/node_modules/') || relPath.includes('\\node_modules\\')) {
    return source;
  }

  console.log(`[varlock-turbopack] processing: ${relPath}`);

  // quick bail if no ENV references
  if (!source.includes('ENV')) return source;

  const rawEnv = process.env.__VARLOCK_ENV;
  if (!rawEnv) {
    console.log(`[varlock-turbopack] no __VARLOCK_ENV, skipping: ${relPath}`);
    return source;
  }

  let envGraph: SerializedEnvGraph;
  try {
    envGraph = JSON.parse(rawEnv);
  } catch {
    return source;
  }

  let result = source;

  const hasVarlockImport = VARLOCK_ENV_IMPORT_RE.test(result);
  const isProxyFile = /[/\\]proxy\.[jt]sx?$/.test(this.resourcePath);
  console.log(`[varlock-turbopack] ${relPath}: hasVarlockImport=${hasVarlockImport}, isProxyFile=${isProxyFile}, hasInlineCode=${!!varlockEnvInlineCode}`);

  if (hasVarlockImport) {
    if (isProxyFile && varlockEnvInlineCode) {
      // proxy.ts/js: Turbopack can't resolve varlock/env here, so inline the entire
      // varlock/env module source. We set process.env.__VARLOCK_ENV first so that
      // the auto-init inside the bundled code picks it up.
      const inlineCode = [
        `process.env.__VARLOCK_ENV = ${JSON.stringify(rawEnv)};`,
        varlockEnvInlineCode,
      ].join('\n');
      result = result.replace(VARLOCK_ENV_IMPORT_RE, inlineCode);
      console.log(`[varlock-turbopack] ✅ inlined varlock/env into ${relPath} (${inlineCode.length} bytes)`);
    } else if (isProxyFile && !varlockEnvInlineCode) {
      console.warn('[varlock-turbopack] ⚠️ proxy file has varlock/env import but inline bundle not available!');
    } else {
      // other files: just ensure __VARLOCK_ENV is set before the import
      result = `process.env.__VARLOCK_ENV = ${JSON.stringify(rawEnv)};\n${result}`;
      console.log(`[varlock-turbopack] prepended __VARLOCK_ENV to ${relPath}`);
    }
  }

  // static replacements for non-sensitive env vars
  for (const [key, item] of Object.entries(envGraph.config)) {
    if (item.isSensitive) continue;

    // match ENV.KEY as a member expression (word boundary before ENV, not followed by more identifier chars)
    const pattern = new RegExp(`\\bENV\\.${escapeRegExp(key)}(?![\\w$])`, 'g');
    result = result.replace(pattern, JSON.stringify(item.value));
  }

  return result;
}

// CJS export required for webpack loader-runner compatibility
module.exports = turbopackLoader;
