export type TypeGenCommentStyle = '//' | '#';

/** stable substring of the banner, used to recognize our own generated files */
export const AUTOGENERATED_FILE_MARKER = 'THIS IS AN AUTOGENERATED FILE';

const AUTOGENERATED_BANNER_LINES = [
  '🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑',
  `🛑 ${AUTOGENERATED_FILE_MARKER} - DO NOT EDIT DIRECTLY 🛑`,
  '🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑',
];

export function getAutogeneratedBanner(commentStyle: TypeGenCommentStyle): string {
  // no leading blank line — a blank first line is non-idiomatic everywhere and gofmt strips it
  return AUTOGENERATED_BANNER_LINES.map((line) => `${commentStyle} ${line}`).join('\n');
}
