export type TypeGenCommentStyle = '//' | '#';

const AUTOGENERATED_BANNER_LINES = [
  '🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑',
  '🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑',
  '🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑',
];

export function getAutogeneratedBanner(commentStyle: TypeGenCommentStyle): string {
  const body = AUTOGENERATED_BANNER_LINES.map((line) => `${commentStyle} ${line}`).join('\n');
  return commentStyle === '//' ? `\n${body}` : body;
}
