import fs from 'node:fs';
import path from 'node:path';
import { AUTOGENERATED_FILE_MARKER } from './banners';

/**
 * `NodeJS.ProcessEnv` is a single global interface, so two declarations of it must have
 * *identical* members for every shared key or TypeScript errors (TS2320 - "Interface
 * 'ProcessEnv' cannot simultaneously extend types ... are not identical"). Our augmentation can
 * never match another tool's: an optional item alone (`FOO?: string` vs `FOO: string`) is enough
 * to conflict, as are enums and booleans, which we type as literal unions.
 *
 * The best known example is `wrangler types`, which writes a `NodeJS.ProcessEnv` augmentation
 * into `worker-configuration.d.ts` covering every var and secret. Rather than detect Cloudflare
 * (or any other platform - infra-as-code setups may not have a wrangler config at all), we look
 * for the thing that actually collides: an existing ProcessEnv declaration.
 *
 * Note the failure bias. Missing a declaration is safe: we keep emitting what we emit today, and
 * if nothing else declares ProcessEnv there was no conflict to avoid. Matching too eagerly would
 * silently drop typing, so the generated file names the file we found.
 */

/**
 * Only the head of each file is scanned. These declarations sit at the top of generated files
 * (wrangler writes env types first, then ~1MB of runtime types after a `// Begin runtime types`
 * marker), and codegen runs on every load, so slurping whole files would be wasteful.
 */
const MAX_SCAN_BYTES = 64 * 1024;

async function readFileHead(filePath: string, maxBytes = MAX_SCAN_BYTES): Promise<string | undefined> {
  let fileHandle;
  try {
    fileHandle = await fs.promises.open(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    const { bytesRead } = await fileHandle.read(buffer, 0, maxBytes, 0);
    return buffer.subarray(0, bytesRead).toString('utf-8');
  } catch {
    // unreadable (deleted mid-scan, permissions, ...) - treat as "no declaration found"
    return undefined;
  } finally {
    await fileHandle?.close().catch(() => undefined);
  }
}

// Neither comments nor string/template literals are declaration syntax: a `'}'` literal would
// close a namespace early (missing a real conflict), while `'interface ProcessEnv'` in a comment
// or a literal would fake one. Both token classes are alternatives of ONE regex so a single
// left-to-right pass consumes whichever opens first: stripping either class ahead of the other
// lets it be spoofed (`// don't` eating real code, or `type M = '//'` hiding the rest of a line).
const COMMENTS_AND_LITERALS = new RegExp([
  /\/\*[\s\S]*?\*\//, // block comment
  /\/\/[^\n]*/, // line comment
  /'(?:[^'\\\n]|\\.)*'/, // single-quoted
  /"(?:[^"\\\n]|\\.)*"/, // double-quoted
  /`(?:[^`\\]|\\.)*`/, // template literal
].map((r) => r.source).join('|'), 'g');

/** Reduce a source file to just the parts that can be declaration syntax. */
function stripNonSyntax(src: string): string {
  // replaced with a space rather than removed, so neighbouring tokens can't fuse
  return src.replace(COMMENTS_AND_LITERALS, ' ');
}

const NODEJS_NAMESPACE_OPEN = /\bnamespace\s+NodeJS\s*\{/g;
const PROCESS_ENV_INTERFACE = /\binterface\s+ProcessEnv\b/;

/**
 * True when the source declares `interface ProcessEnv` *within* a `namespace NodeJS` block. Both
 * names have to be checked together: `interface ProcessEnvExtra` next to an unrelated
 * `namespace NodeJS { interface Process {} }` isn't a conflict, and wrongly treating it as one
 * would silently drop typing that was fine.
 *
 * Deliberately matched by structure rather than by any one tool's output shape, which we don't
 * control and which changes: this covers both `declare namespace NodeJS { ... }` (what wrangler
 * writes) and the `declare global { namespace NodeJS { ... } }` form we emit ourselves.
 *
 * This is a scan, not a parser, so pathological input can still fool it. That is an acceptable
 * trade here: a missed declaration just leaves today's behaviour in place (and the conflict it
 * would have caused is a loud `TS2320` with a documented one-arg fix), while the false-positive
 * direction, which silently drops typing, needs the literal text of a declaration to appear
 * outside comments and strings.
 */
function declaresProcessEnv(rawSrc: string): boolean {
  const src = stripNonSyntax(rawSrc);
  NODEJS_NAMESPACE_OPEN.lastIndex = 0;
  let match = NODEJS_NAMESPACE_OPEN.exec(src);
  while (match) {
    // walk from the namespace's opening brace to its matching close, so a `ProcessEnv` declared
    // after the block (or in a sibling one) doesn't count as being inside it
    let depth = 1;
    let i = match.index + match[0].length;
    const bodyStart = i;
    while (i < src.length && depth > 0) {
      if (src[i] === '{') depth++;
      else if (src[i] === '}') depth--;
      i++;
    }
    if (PROCESS_ENV_INTERFACE.test(src.slice(bodyStart, depth === 0 ? i - 1 : undefined))) return true;
    match = NODEJS_NAMESPACE_OPEN.exec(src);
  }
  return false;
}

/**
 * Look for a `.d.ts` alongside the schema (and alongside the generated file, when that lives
 * elsewhere) that already augments `NodeJS.ProcessEnv`.
 *
 * Returns the absolute path of the first match, or undefined. Our own generated files are
 * skipped - they carry the autogenerated banner, so a second `@generateTsTypes` writing into the
 * same directory doesn't look like a foreign declaration.
 */
export async function findConflictingProcessEnvAugmentation(opts: {
  /** directories to scan, non-recursively */
  dirs: Array<string>;
  /** absolute path of the file being generated, never treated as a conflict */
  outputPath: string;
}): Promise<string | undefined> {
  const scanned = new Set<string>();
  for (const dir of opts.dirs) {
    const resolvedDir = path.resolve(dir);
    if (scanned.has(resolvedDir)) continue;
    scanned.add(resolvedDir);

    let entries: Array<string>;
    try {
      entries = await fs.promises.readdir(resolvedDir);
    } catch {
      continue;
    }

    for (const entry of entries.sort()) {
      if (!entry.endsWith('.d.ts')) continue;
      const filePath = path.join(resolvedDir, entry);
      if (filePath === path.resolve(opts.outputPath)) continue;
      const src = await readFileHead(filePath);
      if (!src) continue;
      if (src.includes(AUTOGENERATED_FILE_MARKER)) continue;
      if (declaresProcessEnv(src)) return filePath;
    }
  }
  return undefined;
}
