import fs from 'node:fs';
import path from 'node:path';
import { AUTOGENERATED_FILE_MARKER } from './banners';

/**
 * `NodeJS.ProcessEnv` is a single global interface, so two declarations of it must have
 * *identical* members for every shared key or TypeScript errors (TS2320 - "Interface
 * 'ProcessEnv' cannot simultaneously extend types ... are not identical"). Our augmentation can
 * never match another tool's: an optional item alone (`FOO?: string` vs `FOO: string`) is enough
 * to conflict, as are enums and booleans, which we type as literal unions.
 *
 * The best known example is `wrangler types`, which writes a `NodeJS.ProcessEnv` augmentation
 * into `worker-configuration.d.ts` covering every var and secret. Rather than detect Cloudflare
 * (or any other platform - infra-as-code setups may not have a wrangler config at all), we look
 * for the thing that actually collides: an existing ProcessEnv declaration.
 *
 * Note the failure bias. Missing a declaration is safe: we keep emitting what we emit today, and
 * if nothing else declares ProcessEnv there was no conflict to avoid. Matching too eagerly would
 * silently drop typing, so the generated file names the file we found.
 */

/**
 * Only the head of each file is scanned. These declarations sit at the top of generated files
 * (wrangler writes env types first, then ~1MB of runtime types after a `// Begin runtime types`
 * marker), and codegen runs on every load, so slurping whole files would be wasteful.
 */
const MAX_SCAN_BYTES = 64 * 1024;

async function readFileHead(filePath: string, maxBytes = MAX_SCAN_BYTES): Promise<string | undefined> {
  let fileHandle;
  try {
    fileHandle = await fs.promises.open(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    const { bytesRead } = await fileHandle.read(buffer, 0, maxBytes, 0);
    return buffer.subarray(0, bytesRead).toString('utf-8');
  } catch {
    // unreadable (deleted mid-scan, permissions, ...) - treat as "no declaration found"
    return undefined;
  } finally {
    await fileHandle?.close().catch(() => undefined);
  }
}

// Comments and string/template literals are not declaration syntax, and either can spoof the
// match in both directions (prose that reads like a declaration, or a stray `}` that hides one).
// Both classes are alternatives of ONE regex, so a single left-to-right pass takes whichever
// opens first: stripping either class ahead of the other lets it be spoofed (`// don't` eating
// real code, or `type M = '//'` hiding the rest of a line). Replaced with a space, not removed,
// so neighbouring tokens can't fuse.
const COMMENTS_AND_LITERALS = new RegExp([
  /\/\*[\s\S]*?\*\//, // block comment
  /\/\/[^\n]*/, // line comment
  /'(?:[^'\\\n]|\\.)*'/, // single-quoted
  /"(?:[^"\\\n]|\\.)*"/, // double-quoted
  /`(?:[^`\\]|\\.)*`/, // template literal
].map((r) => r.source).join('|'), 'g');

/**
 * `interface ProcessEnv` opening a `namespace NodeJS` block. The two tokens must be adjacent
 * (nothing but whitespace, modifiers, or `}`-free text between them), which is what every
 * generator that writes one of these actually emits, ours included:
 *
 *     declare namespace NodeJS { interface ProcessEnv extends ... {} }     // wrangler
 *     declare global { namespace NodeJS { interface ProcessEnv ... } }     // varlock
 *
 * Requiring adjacency is what keeps this honest without a parser. `[^}]` can't run past the end
 * of the first member, so a `ProcessEnv` declared *after* the namespace closes can't match, and
 * `\b` keeps `interface ProcessEnvExtra` out.
 */
const NODEJS_PROCESS_ENV = /\bnamespace\s+NodeJS\s*\{[^}]{0,400}?\binterface\s+ProcessEnv\b/;

/**
 * True when the source looks like it declares `NodeJS.ProcessEnv`.
 *
 * A heuristic on purpose. It is deliberately biased to miss rather than over-match, because the
 * two failure directions are not symmetric: a miss just leaves today's behaviour in place, and
 * the conflict it would have avoided shows up as a loud `TS2320` with a documented one-arg fix
 * (`processEnv=none`), whereas a false positive silently drops typing that was fine. So anything
 * it can't read confidently (a declaration that isn't the first member of its namespace, or one
 * buried in an exotic literal the strip above doesn't recognize) simply doesn't match, and lands
 * the user on the error and the documented fix. Matching by structure rather than by any one tool's output shape also keeps
 * it from rotting when that output changes.
 */
function declaresProcessEnv(rawSrc: string): boolean {
  return NODEJS_PROCESS_ENV.test(rawSrc.replace(COMMENTS_AND_LITERALS, ' '));
}

/**
 * Look for a `.d.ts` alongside the schema (and alongside the generated file, when that lives
 * elsewhere) that already augments `NodeJS.ProcessEnv`.
 *
 * Returns the absolute path of the first match, or undefined. Our own generated files are
 * skipped - they carry the autogenerated banner, so a second `@generateTsTypes` writing into the
 * same directory doesn't look like a foreign declaration.
 */
export async function findConflictingProcessEnvAugmentation(opts: {
  /** directories to scan, non-recursively */
  dirs: Array<string>;
  /** absolute path of the file being generated, never treated as a conflict */
  outputPath: string;
}): Promise<string | undefined> {
  const scanned = new Set<string>();
  for (const dir of opts.dirs) {
    const resolvedDir = path.resolve(dir);
    if (scanned.has(resolvedDir)) continue;
    scanned.add(resolvedDir);

    let entries: Array<string>;
    try {
      entries = await fs.promises.readdir(resolvedDir);
    } catch {
      continue;
    }

    for (const entry of entries.sort()) {
      if (!entry.endsWith('.d.ts')) continue;
      const filePath = path.join(resolvedDir, entry);
      if (filePath === path.resolve(opts.outputPath)) continue;
      const src = await readFileHead(filePath);
      if (!src) continue;
      if (src.includes(AUTOGENERATED_FILE_MARKER)) continue;
      if (declaresProcessEnv(src)) return filePath;
    }
  }
  return undefined;
}
