import fs from 'node:fs';
import path from 'node:path';
import { AUTOGENERATED_FILE_MARKER } from './banners';

/**
 * `NodeJS.ProcessEnv` is a single global interface, so two declarations of it must have
 * *identical* members for every shared key or TypeScript errors (TS2320 - "Interface
 * 'ProcessEnv' cannot simultaneously extend types ... are not identical"). Our augmentation can
 * never match another tool's: an optional item alone (`FOO?: string` vs `FOO: string`) is enough
 * to conflict, as are enums and booleans, which we type as literal unions.
 *
 * The best known example is `wrangler types`, which writes a `NodeJS.ProcessEnv` augmentation
 * into `worker-configuration.d.ts` covering every var and secret. Rather than detect Cloudflare
 * (or any other platform - infra-as-code setups may not have a wrangler config at all), we look
 * for the thing that actually collides: an existing ProcessEnv declaration.
 *
 * Note the failure bias. Missing a declaration is safe: we keep emitting what we emit today, and
 * if nothing else declares ProcessEnv there was no conflict to avoid. Matching too eagerly would
 * silently drop typing, so the generated file names the file we found.
 */

/**
 * Only the head of each file is scanned. These declarations sit at the top of generated files
 * (wrangler writes env types first, then ~1MB of runtime types after a `// Begin runtime types`
 * marker), and codegen runs on every load, so slurping whole files would be wasteful.
 */
const MAX_SCAN_BYTES = 64 * 1024;

async function readFileHead(filePath: string, maxBytes = MAX_SCAN_BYTES): Promise<string | undefined> {
  let fileHandle;
  try {
    fileHandle = await fs.promises.open(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    const { bytesRead } = await fileHandle.read(buffer, 0, maxBytes, 0);
    return buffer.subarray(0, bytesRead).toString('utf-8');
  } catch {
    // unreadable (deleted mid-scan, permissions, ...) - treat as "no declaration found"
    return undefined;
  } finally {
    await fileHandle?.close().catch(() => undefined);
  }
}

/**
 * Both signals must be present. Checking for the two names rather than matching a specific shape
 * keeps this from coupling to any one tool's output, which we don't control and which changes.
 */
function declaresProcessEnv(src: string): boolean {
  return src.includes('namespace NodeJS') && src.includes('interface ProcessEnv');
}

/**
 * Look for a `.d.ts` alongside the schema (and alongside the generated file, when that lives
 * elsewhere) that already augments `NodeJS.ProcessEnv`.
 *
 * Returns the absolute path of the first match, or undefined. Our own generated files are
 * skipped - they carry the autogenerated banner, so a second `@generateTsTypes` writing into the
 * same directory doesn't look like a foreign declaration.
 */
export async function findConflictingProcessEnvAugmentation(opts: {
  /** directories to scan, non-recursively */
  dirs: Array<string>;
  /** absolute path of the file being generated, never treated as a conflict */
  outputPath: string;
}): Promise<string | undefined> {
  const scanned = new Set<string>();
  for (const dir of opts.dirs) {
    const resolvedDir = path.resolve(dir);
    if (scanned.has(resolvedDir)) continue;
    scanned.add(resolvedDir);

    let entries: Array<string>;
    try {
      entries = await fs.promises.readdir(resolvedDir);
    } catch {
      continue;
    }

    for (const entry of entries.sort()) {
      if (!entry.endsWith('.d.ts')) continue;
      const filePath = path.join(resolvedDir, entry);
      if (filePath === path.resolve(opts.outputPath)) continue;
      const src = await readFileHead(filePath);
      if (!src) continue;
      if (src.includes(AUTOGENERATED_FILE_MARKER)) continue;
      if (declaresProcessEnv(src)) return filePath;
    }
  }
  return undefined;
}
