import Foundation
import CryptoKit

/// The varlock ECIES wire format, shared by every backend.
///
///   version(1) | ephemeralPub(65) | nonce(12) | ciphertext(N) | tag(16)
///
/// P-256 ECDH, HKDF-SHA256 (salt "varlock-ecies-v1", info = ephemeralPub || recipientPub),
/// AES-256-GCM. This is the same scheme `SecureEnclaveManager` implements against a
/// Secure Enclave key; here it is expressed once, against any key that can perform
/// the key agreement, so software identity keys and enclave keys share one code path.
///
/// The TypeScript side (`packages/varlock/src/lib/local-encrypt/crypto.ts`) implements
/// the identical format, and `EciesCompatTests` pins that with a fixture generated by it.
public enum Ecies {
    /// Payload encrypted directly to a device key (Secure Enclave / TPM / file)
    public static let devicePayloadVersion: UInt8 = 0x01
    /// Payload encrypted to an identity public key, which is itself wrapped to a device key
    public static let identityPayloadVersion: UInt8 = 0x02

    public static let hkdfSalt = Data("varlock-ecies-v1".utf8)

    static let publicKeyLength = 65
    static let nonceLength = 12
    static let tagLength = 16
    static let headerLength = 1 + publicKeyLength + nonceLength

    public enum EciesError: LocalizedError {
        case payloadTooShort
        case unsupportedVersion(UInt8)
        case malformedPrivateKey(String)
        case decryptionFailed(String)

        public var errorDescription: String? {
            switch self {
            case .payloadTooShort: return "Payload too short"
            case .unsupportedVersion(let v): return "Unsupported encrypted payload version \(v); upgrade varlock"
            case .malformedPrivateKey(let msg): return "Malformed private key: \(msg)"
            case .decryptionFailed(let msg): return "Unable to decrypt value: \(msg)"
            }
        }
    }

    // MARK: - HKDF

    /// HKDF-SHA256 (RFC 5869), matching `SecureEnclaveManager.deriveKey` and the TS port.
    public static func deriveKey(
        sharedSecret: Data,
        salt: Data,
        info: Data,
        outputByteCount: Int
    ) -> SymmetricKey {
        let prk = HMAC<SHA256>.authenticationCode(for: sharedSecret, using: SymmetricKey(data: salt))
        let prkData = Data(prk)

        var okm = Data()
        var t = Data()
        var counter: UInt8 = 1
        while okm.count < outputByteCount {
            var input = t
            input.append(info)
            input.append(counter)
            t = Data(HMAC<SHA256>.authenticationCode(for: input, using: SymmetricKey(data: prkData)))
            okm.append(t)
            counter += 1
        }
        return SymmetricKey(data: okm.prefix(outputByteCount))
    }

    // MARK: - Encrypt

    /// Encrypt to a recipient public key. Needs no private key and no auth gate.
    public static func encrypt(
        plaintext: Data,
        to recipientPublicKey: P256.KeyAgreement.PublicKey,
        version: UInt8
    ) throws -> Data {
        let recipientPubData = Data(recipientPublicKey.x963Representation)

        let ephemeralPrivateKey = P256.KeyAgreement.PrivateKey()
        let ephemeralPubData = Data(ephemeralPrivateKey.publicKey.x963Representation)

        let sharedSecret = try ephemeralPrivateKey.sharedSecretFromKeyAgreement(with: recipientPublicKey)
        var sharedSecretData = sharedSecret.withUnsafeBytes { Data($0) }
        defer { scrub(&sharedSecretData) }

        let symmetricKey = deriveKey(
            sharedSecret: sharedSecretData,
            salt: hkdfSalt,
            info: ephemeralPubData + recipientPubData,
            outputByteCount: 32
        )

        let sealedBox = try AES.GCM.seal(plaintext, using: symmetricKey)

        var payload = Data()
        payload.append(version)
        payload.append(ephemeralPubData)
        payload.append(contentsOf: sealedBox.nonce)
        payload.append(sealedBox.ciphertext)
        payload.append(sealedBox.tag)
        return payload
    }

    /// Encrypt to a recipient public key given in its raw x9.63 (65 byte) form.
    public static func encrypt(plaintext: Data, toPublicKeyData data: Data, version: UInt8) throws -> Data {
        let publicKey = try P256.KeyAgreement.PublicKey(x963Representation: data)
        return try encrypt(plaintext: plaintext, to: publicKey, version: version)
    }

    // MARK: - Decrypt

    /// Split a payload into its parts, validating the framing but not the key.
    static func parse(payload: Data) throws -> (version: UInt8, ephemeralPub: Data, nonce: Data, ciphertext: Data, tag: Data) {
        guard payload.count > headerLength + tagLength else {
            throw EciesError.payloadTooShort
        }
        // Data slices keep the parent's indices, so rebase before slicing.
        let bytes = Data(payload)
        let version = bytes[0]
        let ephemeralPub = bytes[1..<(1 + publicKeyLength)]
        let nonce = bytes[(1 + publicKeyLength)..<headerLength]
        let rest = bytes[headerLength...]
        let ciphertext = rest.dropLast(tagLength)
        let tag = rest.suffix(tagLength)
        return (version, Data(ephemeralPub), Data(nonce), Data(ciphertext), Data(tag))
    }

    /// Decrypt using any key that can run the P-256 key agreement (software or enclave).
    ///
    /// `acceptedVersions` is checked against the payload's version byte. That byte is
    /// outside the AEAD tag, so it is a routing hint rather than an authenticated
    /// claim: flipping it only sends the payload at the wrong key, where it fails.
    public static func decrypt(
        payload: Data,
        using privateKey: some EciesKeyAgreementKey,
        acceptedVersions: Set<UInt8>
    ) throws -> Data {
        let parts = try parse(payload: payload)
        guard acceptedVersions.contains(parts.version) else {
            throw EciesError.unsupportedVersion(parts.version)
        }

        let ephemeralPublicKey = try P256.KeyAgreement.PublicKey(x963Representation: parts.ephemeralPub)
        var sharedSecretData = try privateKey.sharedSecretBytes(with: ephemeralPublicKey)
        defer { scrub(&sharedSecretData) }

        let symmetricKey = deriveKey(
            sharedSecret: sharedSecretData,
            salt: hkdfSalt,
            info: parts.ephemeralPub + privateKey.publicKeyX963,
            outputByteCount: 32
        )

        do {
            let sealedBox = try AES.GCM.SealedBox(
                nonce: try AES.GCM.Nonce(data: parts.nonce),
                ciphertext: parts.ciphertext,
                tag: parts.tag
            )
            return try AES.GCM.open(sealedBox, using: symmetricKey)
        } catch {
            throw EciesError.decryptionFailed(error.localizedDescription)
        }
    }
}

// MARK: - Key agreement abstraction

/// A P-256 key that can perform ECDH, whether it lives in software or in the enclave.
public protocol EciesKeyAgreementKey {
    var publicKeyX963: Data { get }
    func sharedSecretBytes(with publicKey: P256.KeyAgreement.PublicKey) throws -> Data
}

extension P256.KeyAgreement.PrivateKey: EciesKeyAgreementKey {
    public var publicKeyX963: Data { Data(publicKey.x963Representation) }

    public func sharedSecretBytes(with publicKey: P256.KeyAgreement.PublicKey) throws -> Data {
        let secret = try sharedSecretFromKeyAgreement(with: publicKey)
        return secret.withUnsafeBytes { Data($0) }
    }
}

extension SecureEnclave.P256.KeyAgreement.PrivateKey: EciesKeyAgreementKey {
    public var publicKeyX963: Data { Data(publicKey.x963Representation) }

    public func sharedSecretBytes(with publicKey: P256.KeyAgreement.PublicKey) throws -> Data {
        let secret = try sharedSecretFromKeyAgreement(with: publicKey)
        return secret.withUnsafeBytes { Data($0) }
    }
}

// MARK: - Private key import

public enum IdentityKeyImport {
    /// Load a P-256 private key from the PKCS#8 DER the TS side produces.
    ///
    /// `crypto.ts` exports identity private keys as base64 PKCS#8, so that is what
    /// the daemon finds inside a wrap blob. We pull the 32-byte scalar out ourselves
    /// rather than relying on CryptoKit's DER parsing accepting this exact profile,
    /// and hand it straight to CryptoKit so the raw scalar lives in one place we
    /// can scrub.
    public static func p256KeyAgreementKey(fromPkcs8 der: Data) throws -> P256.KeyAgreement.PrivateKey {
        var scalar = try extractP256Scalar(fromPkcs8: der)
        defer { scrub(&scalar) }
        do {
            return try P256.KeyAgreement.PrivateKey(rawRepresentation: scalar)
        } catch {
            throw Ecies.EciesError.malformedPrivateKey(error.localizedDescription)
        }
    }

    /// Pull the raw 32-byte private scalar out of a PKCS#8 `PrivateKeyInfo`.
    ///
    /// Structure walked (all lengths short-form or 0x81/0x82 long-form):
    ///   SEQUENCE { INTEGER version, SEQUENCE algorithm, OCTET STRING privateKey }
    /// and inside that OCTET STRING, an SEC1 `ECPrivateKey`:
    ///   SEQUENCE { INTEGER version, OCTET STRING privateKey(32), ... }
    static func extractP256Scalar(fromPkcs8 der: Data) throws -> Data {
        var reader = DerReader(Data(der))
        let outer = try reader.readSequenceBody()

        var top = DerReader(outer)
        _ = try top.readElement(tag: 0x02)      // version INTEGER
        _ = try top.readElement(tag: 0x30)      // AlgorithmIdentifier SEQUENCE
        let inner = try top.readElement(tag: 0x04) // privateKey OCTET STRING

        var sec1 = DerReader(inner)
        let sec1Body = try sec1.readSequenceBody()
        var sec1Fields = DerReader(sec1Body)
        _ = try sec1Fields.readElement(tag: 0x02) // version INTEGER
        let scalar = try sec1Fields.readElement(tag: 0x04)

        guard scalar.count == 32 else {
            throw Ecies.EciesError.malformedPrivateKey("expected a 32 byte P-256 scalar, got \(scalar.count)")
        }
        return scalar
    }
}

/// Minimal DER walker: enough to step through a PKCS#8 P-256 private key.
struct DerReader {
    private let bytes: Data
    private var offset: Int

    init(_ data: Data) {
        self.bytes = Data(data)
        self.offset = 0
    }

    /// Read one element with the expected tag and return its contents.
    mutating func readElement(tag expected: UInt8) throws -> Data {
        guard offset < bytes.count else {
            throw Ecies.EciesError.malformedPrivateKey("truncated DER")
        }
        let tag = bytes[offset]
        guard tag == expected else {
            throw Ecies.EciesError.malformedPrivateKey(
                String(format: "expected DER tag 0x%02x, found 0x%02x", expected, tag)
            )
        }
        offset += 1
        let length = try readLength()
        guard offset + length <= bytes.count else {
            throw Ecies.EciesError.malformedPrivateKey("DER element runs past end of buffer")
        }
        let contents = bytes[offset..<(offset + length)]
        offset += length
        return Data(contents)
    }

    mutating func readSequenceBody() throws -> Data {
        return try readElement(tag: 0x30)
    }

    private mutating func readLength() throws -> Int {
        guard offset < bytes.count else {
            throw Ecies.EciesError.malformedPrivateKey("truncated DER length")
        }
        let first = bytes[offset]
        offset += 1
        if first & 0x80 == 0 { return Int(first) }

        let byteCount = Int(first & 0x7f)
        guard byteCount > 0, byteCount <= 4, offset + byteCount <= bytes.count else {
            throw Ecies.EciesError.malformedPrivateKey("unsupported DER length encoding")
        }
        var value = 0
        for _ in 0..<byteCount {
            value = (value << 8) | Int(bytes[offset])
            offset += 1
        }
        return value
    }
}

// MARK: - Scrubbing

/// Zero a buffer in place, defeating the optimizer (`memset_s`).
///
/// Key material only ever lives in CryptoKit types or in buffers run through
/// this, never in a Swift `String` (whose storage we cannot reclaim).
public func scrub(_ data: inout Data) {
    guard !data.isEmpty else { return }
    data.withUnsafeMutableBytes { raw in
        guard let base = raw.baseAddress else { return }
        _ = memset_s(base, raw.count, 0, raw.count)
    }
    data.removeAll(keepingCapacity: false)
}

public func scrub(_ bytes: inout [UInt8]) {
    guard !bytes.isEmpty else { return }
    bytes.withUnsafeMutableBufferPointer { buf in
        guard let base = buf.baseAddress else { return }
        _ = memset_s(base, buf.count, 0, buf.count)
    }
    bytes.removeAll(keepingCapacity: false)
}
