import crypto from 'node:crypto';
import fs from 'node:fs';
import _ from '@env-spec/utils/my-dash';
import type { EnvGraph } from './env-graph';
import type { TypeGenItemInfo } from './config-item';


const AUTOGENERATED_FILE_BANNER = `
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
`;


const ICON_SIZE = 20;

let iconCacheFolderInit = false;
const iconInMemoryCache: Record<string, string> = {};

async function fetchIconSvg(
  iconifyName: string,
  color = '808080', // neutral gray that should appear on black or white bg
  iconCacheFolder = '/tmp/varlock-icon-cache', // TODO: maybe move icon cache to ~/.varlock dir?
) {
  // some notes about icons
  // - using a URL that points to an svg doesn't work (but png/jpg do work)
  // - but embedding data url with an svg works fine
  // - we are fetching them on demand and caching them
  // - and then applying a color if one is set or falling back to a neutral gray that should show up on either black or white

  if (!iconCacheFolderInit) {
    fs.mkdirSync(iconCacheFolder, { recursive: true });
    iconCacheFolderInit = true;
  }

  const iconPath = `${iconCacheFolder}/${iconifyName}-${ICON_SIZE}.svg`;

  let svgSrc: string | undefined;
  if (iconInMemoryCache[iconPath]) {
    svgSrc = iconInMemoryCache[iconPath];
  } else if (fs.existsSync(iconPath)) {
    const svgFileBuffer = await fs.promises.readFile(iconPath, 'utf-8');
    svgSrc = svgFileBuffer.toString();
    iconInMemoryCache[iconPath] = svgSrc;
  } else {
    try {
      const iconSvg = await fetch(`https://api.iconify.design/${iconifyName.replace(':', '/')}.svg?height=${ICON_SIZE}`);
      svgSrc = await iconSvg.text();
    } catch (err) {
      return;
    }
    if (!svgSrc) return;


    // TODO: optionally re-enable svgo - but only as a peer dependency?
    // // run it through svgo to try to shrink it down a little
    // const optimizedSvgResult = optimize(svgSrc, {
    //   multipass: true,
    // });
    // if (!optimizedSvgResult.data) throw new Error(`Failed to optimize SVG icon - ${iconifyName}`);
    // svgSrc = optimizedSvgResult.data as string;

    if (svgSrc) {
      await fs.promises.writeFile(iconPath, svgSrc, 'utf-8');
      iconInMemoryCache[iconPath] = svgSrc;
    }
  }


  const hexColor = color.startsWith('#') ? color : `#${color}`;
  const colorizedSvg = svgSrc.replaceAll('currentColor', hexColor);
  return colorizedSvg;
}


/** Compute the TS type string for an item (extracted for reuse in augmentation blocks) */
function getItemTsType(info: TypeGenItemInfo): string {
  const dataType = info.dataType;
  const dataTypeName = dataType?.name;

  if (dataType) {
    if (dataTypeName === 'number' || dataTypeName === 'port') return 'number';
    if (dataTypeName === 'boolean') return 'boolean';
    if (dataTypeName === 'simple-object') return 'Record<string, any>';
    if (dataTypeName === 'enum') {
      const rawEnumOptions = (dataType._rawDef as any)._rawEnumOptions;
      if (!rawEnumOptions?.length) return 'never';
      return _.map(rawEnumOptions, JSON.stringify).join(' | ');
    }
  }
  return 'string';
}

export async function getTsDefinitionForItem(info: TypeGenItemInfo, indentLevel = 0) {
  const i = _.times(indentLevel, () => '  ').join('');
  const itemSrc = [];

  // TODO: also will need to figure out how we deal with null values
  // since we might need something like `key: string | null` rather than `key?: string`

  const jsDocLines = [];

  jsDocLines.push(`**${info.key}**${info.isSensitive ? ' 🔐 _sensitive_' : ''}`);

  if (info.description) jsDocLines.push(...info.description.split('\n'));
  // type-description?

  const iconName = info.icon;
  if (iconName) {
    // TODO: pass through custom icon color? (already exists on fetchIconSvg)
    const iconSvg = await fetchIconSvg(iconName);
    if (iconSvg) jsDocLines.push(`![icon](data:image/svg+xml;utf-8,${encodeURIComponent(iconSvg)}) `);
  }

  const docsLinks = info.docsLinks;
  if (docsLinks.length) {
    jsDocLines.push('');
    docsLinks.forEach((docsEntry) => {
      // see https://jsdoc.app/tags-see for format info
      const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
      jsDocLines.push(`📚 {@link ${docsLink}}`);
    });
  }

  // more ideas:
  // - we have an `exampleValue` property we could include
  // - there's also a `@example` jsdoc directive which is meant to show a code example
  // - could add info about the original source of an item if it has been picked / imported
  // - could include additional text about type settings / validations

  if (jsDocLines.length === 1) {
    itemSrc.push(`/** ${jsDocLines[0]} */`);
  } else if (jsDocLines.length > 1) {
    itemSrc.push(...[
      '/**',
      // extra 2 trailing spaces are needed to make line breaks visible
      // escape `*/` sequences to prevent premature comment closure
      ..._.flatMap(jsDocLines, (line) => [` * ${line.replace(/\*\//g, '* /')}  `]),
      ' */',
    ]);
  }

  const itemTsType = getItemTsType(info);
  const isRequired = info.isRequired && !info.isRequiredDynamic;
  itemSrc.push(`${info.key}${isRequired ? '' : '?'}: ${itemTsType};`);
  itemSrc.push('');
  return _.map(itemSrc, (line) => `${i}${line}`);
}

export async function generateTsTypesSrc(items: Array<TypeGenItemInfo>) {
  // TODO: first check if schema is valid - we dont care if values are invalid

  const tsSrc = [
    AUTOGENERATED_FILE_BANNER,
    '// @ts-nocheck',
    // might want to add some options to let users inject this, or somehow detect eslint, but fine for now
    '/* eslint-disable */',
    'export type CoercedEnvSchema = {',
  ];

  for (const info of items) {
    // generate the TS type for the item in the full schema
    tsSrc.push(...await getTsDefinitionForItem(info, 1));
  }

  tsSrc.push('};\n');

  // Generate a unique type alias so that `declare module` and `declare global` blocks
  // reference a file-scoped name that won't collide across packages in a monorepo.
  // Without this, multiple env.d.ts files exporting the same `CoercedEnvSchema` /
  // `EnvSchemaAsStrings` names can confuse TS when both are in the same compilation.
  const schemaHash = crypto.createHash('md5')
    .update(items.map((i) => i.key).sort().join(','))
    .digest('hex')
    .slice(0, 8);
  const schemaAlias = `_CoercedEnvSchema_${schemaHash}`;
  const stringsAlias = `_EnvSchemaAsStrings_${schemaHash}`;

  tsSrc.push(`type ${schemaAlias} = CoercedEnvSchema;`);

  const exposedNonSensitiveKeys: Array<string> = [];
  for (const info of items) {
    if (!info.isSensitive) exposedNonSensitiveKeys.push(info.key);
  }

  tsSrc.push(`
declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<${schemaAlias}> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<${schemaAlias}, '${exposedNonSensitiveKeys.join("' | '")}'>> {}
}
`);

  // add types for process.env too
  // remap types for process.env
  // - enums - stay string unions if all options are strings
  // - boolean -> 'true' | 'false'
  // - everything else -> string
  tsSrc.push(`
export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};
`);

  tsSrc.push(`type ${stringsAlias} = EnvSchemaAsStrings;`);

  // TODO: allow user to pass in options to control this?
  // although because we add the @generateTypes decorator an init time
  // we may need our integrations to specify what settings they prefer
  const importMetaEnvTypes = true;
  const processEnvTypes = true;

  const IMPORT_META_AUGMENTATION = `
  // add types for global import.meta.env
  interface ImportMetaEnv extends ${stringsAlias} {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }`;
  const PROCESS_ENV_AUGMENTATION = `
  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends ${stringsAlias} {}
  }`;

  // TODO: should add an option to enable/disable
  tsSrc.push(...[
    'declare global {',
    importMetaEnvTypes && IMPORT_META_AUGMENTATION,
    processEnvTypes && PROCESS_ENV_AUGMENTATION,
    '}',
  ].filter(Boolean));

  return tsSrc.join('\n');
}

export async function generateTypes(graph: EnvGraph, lang: string, typesPath: string) {
  if (lang !== 'ts') throw new Error(`Unsupported @generateTypes lang: ${lang}`);

  // Compute type gen info from non-env-specific definitions only
  // Skip items that exist only in env-specific sources
  const items: Array<TypeGenItemInfo> = [];
  for (const itemKey of graph.sortedConfigKeys) {
    // _VARLOCK_ENV_KEY is infrastructure — not accessed via ENV proxy
    if (itemKey === '_VARLOCK_ENV_KEY') continue;
    const configItem = graph.configSchema[itemKey];
    if (!configItem.defsForTypeGeneration.length) continue;
    items.push(await configItem.getTypeGenInfo());
  }

  const tsSrc = await generateTsTypesSrc(items);
  await fs.promises.writeFile(typesPath, tsSrc, 'utf-8');
}
