import _ from '@env-spec/utils/my-dash';
import { getAutogeneratedBanner } from '../banners';
import {
  type CoercedType,
  type ResolvedFieldType,
} from '../shared';

function getGoCoercedTypeString(coerced: CoercedType): string {
  if (coerced === 'number') return 'float64';
  if (coerced === 'boolean') return 'bool';
  if (coerced === 'object') return 'map[string]any';
  if (typeof coerced === 'object' && 'enum' in coerced) {
    if (!coerced.enum.length) return 'any';
    return 'string';
  }
  return 'string';
}

function snakeCaseToPascalCase(key: string): string {
  return key.split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()).join('');
}

function escapeGoComment(text: string): string {
  return text.replace(/\*\//g, '* /');
}

function buildFieldDocComment(field: ResolvedFieldType): Array<string> {
  const lines: Array<string> = [];
  lines.push(`\t// ${field.key}${field.docs.isSensitive ? ' (sensitive)' : ''}`);

  if (field.docs.description) {
    for (const line of field.docs.description.split('\n')) {
      lines.push(`\t// ${escapeGoComment(line)}`);
    }
  }

  for (const docsEntry of field.docs.docsLinks) {
    const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
    lines.push(`\t// Docs: ${escapeGoComment(docsLink)}`);
  }

  if (field.docs.isDeprecated) {
    lines.push(`\t// Deprecated${field.docs.deprecationMessage ? `: ${escapeGoComment(field.docs.deprecationMessage)}` : ''}`);
  }

  return lines;
}

function formatGoStruct(
  structName: string,
  doc: string,
  fields: Array<ResolvedFieldType>,
  getType: (field: ResolvedFieldType) => string,
): Array<string> {
  const lines = [
    '',
    `// ${escapeGoComment(doc)}`,
    `type ${structName} struct {`,
  ];

  if (!fields.length) {
    lines.push('}');
    return lines;
  }

  for (const field of fields) {
    lines.push(...buildFieldDocComment(field));
    const goType = getType(field);
    const fieldType = field.isRequired ? goType : `*${goType}`;
    lines.push(`\t${snakeCaseToPascalCase(field.key)} ${fieldType} \`env:"${field.key}"\``);
  }

  lines.push('}');
  return lines;
}

export function generateGoTypesSrc(fields: Array<ResolvedFieldType>): string {
  const publicFields = fields.filter((field) => !field.isSensitive);

  const src = [
    getAutogeneratedBanner('//'),
    'package envtypes',
    ...formatGoStruct(
      'CoercedEnvSchema',
      'Coerced env schema (matches varlock coercion).',
      fields,
      (field) => getGoCoercedTypeString(field.coerced),
    ),
    ...formatGoStruct(
      'PublicCoercedEnvSchema',
      'Non-sensitive coerced env schema keys.',
      publicFields,
      (field) => getGoCoercedTypeString(field.coerced),
    ),
    ...formatGoStruct(
      'EnvSchemaAsStrings',
      'Raw values from os.Getenv (always strings).',
      fields,
      () => 'string',
    ),
  ];

  return src.join('\n');
}
