import { getAutogeneratedBanner } from '../banners';
import {
  ENCRYPTED_BLOB_PREFIX,
  getFieldDocLines,
  getSensitiveKeys,
  partitionRepresentableKeys,
  skippedKeysComment,
  type CoercedType,
  type ResolvedFieldType,
} from '../shared';

// neutralize any `*/` so a value in a description or enum option can't close the docblock early
// (a source-injection primitive otherwise) — see the escaped description lines below
function escapeDocblock(text: string): string {
  return text.replace(/\*\//g, '* /');
}

function phpBaseType(coerced: CoercedType): string {
  if (coerced === 'int') return 'int';
  if (coerced === 'number') return 'float';
  if (coerced === 'boolean') return 'bool';
  if (coerced === 'object') return 'array';
  return 'string'; // plain strings + enums (refined via @var)
}

function phpEnumLiteral(option: string | number | boolean): string {
  if (typeof option === 'string') return JSON.stringify(option);
  if (typeof option === 'boolean') return option ? 'true' : 'false';
  return String(option);
}

/** phpstan `@var` refinement when the PHP type hint is broader than the real type (enums, objects). */
function phpVarType(coerced: CoercedType): string | undefined {
  if (coerced === 'object') return 'array<string, mixed>';
  if (typeof coerced === 'object' && 'enum' in coerced && coerced.enum.length) {
    return coerced.enum.map(phpEnumLiteral).join('|');
  }
  return undefined;
}

function phpConstructorParam(field: ResolvedFieldType): Array<string> {
  const typeHint = `${field.isRequired ? '' : '?'}${phpBaseType(field.coerced)}`;
  let varType = phpVarType(field.coerced);
  if (varType && !field.isRequired) varType = `${varType}|null`;

  const docLines = getFieldDocLines(field);
  const doc: Array<string> = [];
  if (docLines.length || varType) {
    doc.push('        /**');
    for (const line of docLines) doc.push(`         * ${escapeDocblock(line)}`);
    // enum options / object shapes flow into @var — escape them too so a `*/` can't break out
    if (varType) doc.push(`         * @var ${escapeDocblock(varType)}`);
    doc.push('         */');
  }
  return [...doc, `        public readonly ${typeHint} $${field.key}${field.isRequired ? '' : ' = null'},`];
}

const PHP_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
// one or more identifiers joined by backslashes, e.g. `App` or `App\Config`
const PHP_NAMESPACE = /^[A-Za-z_][A-Za-z0-9_]*(\\[A-Za-z_][A-Za-z0-9_]*)*$/;

export function generatePhpEnvSrc(
  fields: Array<ResolvedFieldType>,
  opts?: { namespace?: unknown, className?: unknown },
): string {
  // class covers representable keys; skipped keys stay as raw env vars (getenv)
  const { safe, skipped } = partitionRepresentableKeys(fields);

  // optional `class=` / `namespace=` for Composer/PSR-4 projects (default: global `Env`)
  const className = opts?.className === undefined ? 'Env' : String(opts.className);
  if (!PHP_IDENTIFIER.test(className)) {
    throw new Error(`@generatePhpEnv - \`class\` must be a valid PHP class name (got ${JSON.stringify(opts?.className)})`);
  }
  let namespace: string | undefined;
  if (opts?.namespace !== undefined && String(opts.namespace).trim() !== '') {
    namespace = String(opts.namespace).trim();
    if (!PHP_NAMESPACE.test(namespace)) {
      throw new Error(`@generatePhpEnv - \`namespace\` must be a valid PHP namespace (got ${JSON.stringify(opts?.namespace)})`);
    }
  }

  // SENSITIVE_KEYS covers every sensitive key (incl. skipped ones) so redaction doesn't miss them
  const sensitiveKeys = getSensitiveKeys(fields);
  // a PHP constructor cannot declare an optional (defaulted) param before a required one
  const ordered = [...safe].sort((a, b) => Number(b.isRequired) - Number(a.isRequired));

  const src = [
    '<?php',
    getAutogeneratedBanner('//'),
    '',
    // per-file; imposes nothing on callers, but turns blob/schema drift into a clean TypeError.
    // must precede the namespace declaration.
    'declare(strict_types=1);',
    ...(namespace ? ['', `namespace ${namespace};`] : []),
    '',
    ...skippedKeysComment(skipped, '//'),
    `final class ${className}`,
    '{',
    '    /** @var list<string> */',
    `    public const SENSITIVE_KEYS = [${sensitiveKeys.map((k) => `'${k}'`).join(', ')}];`,
    '',
    '    public function __construct(',
    ...ordered.flatMap(phpConstructorParam),
    '    ) {}',
    '',
    '    /** Parse the __VARLOCK_ENV blob (injected by `varlock run`) into a typed Env. */',
    '    public static function load(): self',
    '    {',
    "        $blob = getenv('__VARLOCK_ENV');",
    '        if ($blob === false || $blob === \'\') {',
    "            throw new \\RuntimeException('__VARLOCK_ENV is not set — run your app via `varlock run -- php ...`');",
    '        }',
    `        if (str_starts_with($blob, ${JSON.stringify(ENCRYPTED_BLOB_PREFIX)})) {`,
    "            throw new \\RuntimeException('__VARLOCK_ENV is encrypted and cannot be decrypted here — run under `varlock run`');",
    '        }',
    "        $cfg = json_decode($blob, true, flags: JSON_THROW_ON_ERROR)['config'];",
    '        return new self(',
    // required keys throw a clear error if absent (stale generated file); optional keys default to null
    ...safe.map((f) => `            ${f.key}: $cfg['${f.key}']['value'] ?? ${f.isRequired
      ? `throw new \\RuntimeException('varlock: missing required key ${f.key} in __VARLOCK_ENV')`
      : 'null'},`),
    '        );',
    '    }',
    '}',
    '',
  ];

  return src.join('\n');
}
