import { getAutogeneratedBanner } from '../banners';
import {
  getFieldDocLines,
  getSensitiveKeys,
  type CoercedType,
  type ResolvedFieldType,
} from '../shared';

function phpBaseType(coerced: CoercedType): string {
  if (coerced === 'int') return 'int';
  if (coerced === 'number') return 'float';
  if (coerced === 'boolean') return 'bool';
  if (coerced === 'object') return 'array';
  return 'string'; // plain strings + enums (refined via @var)
}

function phpEnumLiteral(option: string | number | boolean): string {
  if (typeof option === 'string') return JSON.stringify(option);
  if (typeof option === 'boolean') return option ? 'true' : 'false';
  return String(option);
}

/** phpstan `@var` refinement when the PHP type hint is broader than the real type (enums, objects). */
function phpVarType(coerced: CoercedType): string | undefined {
  if (coerced === 'object') return 'array<string, mixed>';
  if (typeof coerced === 'object' && 'enum' in coerced && coerced.enum.length) {
    return coerced.enum.map(phpEnumLiteral).join('|');
  }
  return undefined;
}

function phpConstructorParam(field: ResolvedFieldType): Array<string> {
  const typeHint = `${field.isRequired ? '' : '?'}${phpBaseType(field.coerced)}`;
  let varType = phpVarType(field.coerced);
  if (varType && !field.isRequired) varType = `${varType}|null`;

  const docLines = getFieldDocLines(field);
  const doc: Array<string> = [];
  if (docLines.length || varType) {
    doc.push('        /**');
    for (const line of docLines) doc.push(`         * ${line.replace(/\*\//g, '* /')}`);
    if (varType) doc.push(`         * @var ${varType}`);
    doc.push('         */');
  }
  return [...doc, `        public readonly ${typeHint} $${field.key}${field.isRequired ? '' : ' = null'},`];
}

export function generatePhpEnvSrc(fields: Array<ResolvedFieldType>): string {
  const sensitiveKeys = getSensitiveKeys(fields);
  // a PHP constructor cannot declare an optional (defaulted) param before a required one
  const ordered = [...fields].sort((a, b) => Number(b.isRequired) - Number(a.isRequired));

  const src = [
    '<?php',
    getAutogeneratedBanner('//'),
    '',
    'final class Env',
    '{',
    '    /** @var list<string> */',
    `    public const SENSITIVE_KEYS = [${sensitiveKeys.map((k) => `'${k}'`).join(', ')}];`,
    '',
    '    private static ?self $cached = null;',
    '',
    '    public function __construct(',
    ...ordered.flatMap(phpConstructorParam),
    '    ) {}',
    '',
    '    /** Cached typed env — Env::instance()->SOME_KEY. Loads once on first call. */',
    '    public static function instance(): self',
    '    {',
    '        return self::$cached ??= self::load();',
    '    }',
    '',
    '    /** Parse the __VARLOCK_ENV blob (injected by `varlock run`) into a fresh typed Env. */',
    '    public static function load(): self',
    '    {',
    "        $cfg = json_decode(getenv('__VARLOCK_ENV'), true, flags: JSON_THROW_ON_ERROR)['config'];",
    '        return new self(',
    ...fields.map((f) => `            ${f.key}: $cfg['${f.key}']['value']${f.isRequired ? '' : ' ?? null'},`),
    '        );',
    '    }',
    '}',
    '',
  ];

  return src.join('\n');
}
