import { getAutogeneratedBanner } from '../banners';
import {
  getFieldDocLines,
  getSensitiveKeys,
  type CoercedType,
  type ResolvedFieldType,
} from '../shared';

function getPythonCoercedTypeString(coerced: CoercedType): string {
  if (coerced === 'int') return 'int';
  if (coerced === 'number') return 'float';
  if (coerced === 'boolean') return 'bool';
  if (coerced === 'object') return 'dict[str, Any]';
  if (typeof coerced === 'object' && 'enum' in coerced) {
    if (!coerced.enum.length) return 'str';
    const options = coerced.enum.map((option) => {
      if (typeof option === 'string') return JSON.stringify(option);
      if (typeof option === 'boolean') return option ? 'True' : 'False';
      return String(option);
    });
    return `Literal[${options.join(', ')}]`;
  }
  return 'str';
}

function formatPythonField(field: ResolvedFieldType, typeString: string): Array<string> {
  const docLines = getFieldDocLines(field);
  // single line of docs → inline comment; multiple → comment lines above the field; none → no comment
  if (docLines.length === 1) {
    return [`    ${field.key}: ${typeString}  # ${docLines[0]}`];
  }
  return [
    ...docLines.map((line) => `    # ${line}`),
    `    ${field.key}: ${typeString}`,
  ];
}

function formatPythonTypedDict(
  className: string,
  classDoc: string,
  fields: Array<ResolvedFieldType>,
  getType: (field: ResolvedFieldType) => string,
): Array<string> {
  const lines = [
    '',
    '',
    `class ${className}(TypedDict):`,
    `    """${classDoc}"""`,
  ];

  if (!fields.length) {
    lines.push('    pass');
    return lines;
  }

  for (const field of fields) {
    const baseType = getType(field);
    const typeString = field.isRequired ? baseType : `NotRequired[${baseType}]`;
    lines.push(...formatPythonField(field, typeString));
  }

  return lines;
}

export function generatePythonEnvSrc(fields: Array<ResolvedFieldType>): string {
  const sensitiveKeys = getSensitiveKeys(fields);
  const sensitiveSet = sensitiveKeys.length
    ? `frozenset({${sensitiveKeys.map((k) => JSON.stringify(k)).join(', ')}})`
    : 'frozenset()';

  // only import the typing symbols we actually use — avoids unused-import lint warnings and,
  // notably, keeps the file importable on Python < 3.11 when no field needs `NotRequired`
  const typingImports = ['TypedDict'];
  if (fields.some((f) => f.coerced === 'object')) typingImports.push('Any');
  if (fields.some((f) => typeof f.coerced === 'object' && 'enum' in f.coerced && f.coerced.enum.length)) typingImports.push('Literal');
  if (fields.some((f) => !f.isRequired)) typingImports.push('NotRequired');
  typingImports.sort();

  const src = [
    getAutogeneratedBanner('#'),
    'import json',
    'import os',
    `from typing import ${typingImports.join(', ')}`,
    ...formatPythonTypedDict(
      'CoercedEnvSchema',
      'Coerced env schema (matches varlock coercion).',
      fields,
      (field) => getPythonCoercedTypeString(field.coerced),
    ),
    '',
    '',
    '# Keys whose values are sensitive — use this to build your own redaction / leak-scanning.',
    `SENSITIVE_KEYS: frozenset[str] = ${sensitiveSet}`,
    '',
    '',
    'def load_env() -> CoercedEnvSchema:',
    '    """Parse the `__VARLOCK_ENV` blob (injected by `varlock run`) into typed, coerced values."""',
    '    graph = json.loads(os.environ["__VARLOCK_ENV"])',
    '    return {key: entry["value"] for key, entry in graph["config"].items()}  # type: ignore[return-value]',
    '',
    '',
    '# Eagerly loaded typed env — `from env_types import ENV` then use `ENV["DB_PORT"]`.',
    '# (Requires running under `varlock run`; call load_env() yourself if you need to handle errors.)',
    'ENV: CoercedEnvSchema = load_env()',
    '',
  ];

  return src.join('\n');
}
