import _ from '@env-spec/utils/my-dash';
import { getAutogeneratedBanner } from '../banners';
import {
  type CoercedType,
  type RawStringType,
  type ResolvedFieldType,
} from '../shared';

function getPythonCoercedTypeString(coerced: CoercedType): string {
  if (coerced === 'int') return 'int';
  if (coerced === 'number') return 'float';
  if (coerced === 'boolean') return 'bool';
  if (coerced === 'object') return 'dict[str, object]';
  if (typeof coerced === 'object' && 'enum' in coerced) {
    if (!coerced.enum.length) return 'Never';
    return coerced.enum.map((option) => {
      if (typeof option === 'string') return `Literal[${JSON.stringify(option)}]`;
      if (typeof option === 'boolean') return `Literal[${option ? 'True' : 'False'}]`;
      return `Literal[${option}]`;
    }).join(' | ');
  }
  return 'str';
}

function getPythonRawStringTypeString(rawString: RawStringType): string {
  if (typeof rawString === 'object' && 'boolean' in rawString) {
    return 'Literal["true", "false"]';
  }
  if (typeof rawString === 'object' && 'enum' in rawString) {
    return rawString.enum.map((option) => `Literal[${JSON.stringify(option)}]`).join(' | ');
  }
  return 'str';
}

function escapePythonDocstring(text: string): string {
  return text.replace(/"""/g, '\\"\\"\\"').replace(/\*\//g, '* /');
}

function buildFieldDocLines(field: ResolvedFieldType): Array<string> {
  const lines: Array<string> = [];
  lines.push(`${field.key}${field.docs.isSensitive ? ' (sensitive)' : ''}`);

  if (field.docs.description) {
    lines.push(...field.docs.description.split('\n'));
  }

  for (const docsEntry of field.docs.docsLinks) {
    const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
    lines.push(`Docs: ${docsLink}`);
  }

  if (field.docs.isDeprecated) {
    lines.push(field.docs.deprecationMessage ? `Deprecated: ${field.docs.deprecationMessage}` : 'Deprecated');
  }

  return lines;
}

function formatPythonField(field: ResolvedFieldType, typeString: string): Array<string> {
  const lines: Array<string> = [];
  const docLines = buildFieldDocLines(field);

  if (docLines.length === 1) {
    lines.push(`    ${field.key}: ${typeString}  # ${escapePythonDocstring(docLines[0]!)}`);
  } else if (docLines.length > 1) {
    lines.push('    """');
    for (const line of docLines) {
      lines.push(`    ${escapePythonDocstring(line)}`);
    }
    lines.push('    """');
    lines.push(`    ${field.key}: ${typeString}`);
  } else {
    lines.push(`    ${field.key}: ${typeString}`);
  }

  return lines;
}

function formatPythonTypedDict(
  className: string,
  classDoc: string,
  fields: Array<ResolvedFieldType>,
  getType: (field: ResolvedFieldType) => string,
): Array<string> {
  const lines = [
    '',
    `class ${className}(TypedDict):`,
    `    """${escapePythonDocstring(classDoc)}"""`,
  ];

  if (!fields.length) {
    lines.push('    pass');
    return lines;
  }

  for (const field of fields) {
    const baseType = getType(field);
    const typeString = field.isRequired ? baseType : `NotRequired[${baseType}]`;
    lines.push(...formatPythonField(field, typeString));
  }

  return lines;
}

export function generatePythonTypesSrc(fields: Array<ResolvedFieldType>): string {
  const publicFields = fields.filter((field) => !field.isSensitive);

  const src = [
    getAutogeneratedBanner('#'),
    'from typing import Literal, NotRequired, TypedDict',
    ...formatPythonTypedDict(
      'CoercedEnvSchema',
      'Coerced env schema (matches varlock coercion).',
      fields,
      (field) => getPythonCoercedTypeString(field.coerced),
    ),
    ...formatPythonTypedDict(
      'PublicCoercedEnvSchema',
      'Non-sensitive coerced env schema keys.',
      publicFields,
      (field) => getPythonCoercedTypeString(field.coerced),
    ),
    ...formatPythonTypedDict(
      'EnvSchemaAsStrings',
      'Raw values from os.environ / os.getenv (always strings).',
      fields,
      (field) => getPythonRawStringTypeString(field.rawString),
    ),
  ];

  return src.join('\n');
}
