import _ from '@env-spec/utils/my-dash';
import { RUST_AUTOGENERATED_BANNER } from '../banners';
import {
  envKeyToRustFieldName,
  getRustCoercedTypeString,
  getRustRawStringTypeString,
  type ResolvedFieldType,
} from '../shared';

function escapeRustDoc(text: string): string {
  return text.replace(/\*\//g, '* /');
}

function buildFieldDocComment(field: ResolvedFieldType): Array<string> {
  const lines: Array<string> = [];
  lines.push(`/// **${field.key}**${field.docs.isSensitive ? ' (sensitive)' : ''}`);

  if (field.docs.description) {
    for (const line of field.docs.description.split('\n')) {
      lines.push(`/// ${escapeRustDoc(line)}`);
    }
  }

  for (const docsEntry of field.docs.docsLinks) {
    const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
    lines.push(`/// Docs: ${escapeRustDoc(docsLink)}`);
  }

  if (field.docs.isDeprecated) {
    lines.push(`/// Deprecated${field.docs.deprecationMessage ? `: ${escapeRustDoc(field.docs.deprecationMessage)}` : ''}`);
  }

  if (typeof field.coerced === 'object' && 'enum' in field.coerced && field.coerced.enum.length) {
    const options = field.coerced.enum.map((option) => JSON.stringify(option)).join(' | ');
    lines.push(`/// Valid values: ${options}`);
  }

  return lines;
}

function formatRustStruct(
  structName: string,
  doc: string,
  fields: Array<ResolvedFieldType>,
  getType: (field: ResolvedFieldType) => string,
): Array<string> {
  const lines = [
    '',
    '///',
    `/// ${escapeRustDoc(doc)}`,
    '///',
    '#[derive(Debug, Clone)]',
    `pub struct ${structName} {`,
  ];

  if (!fields.length) {
    lines.push('}');
    return lines;
  }

  for (const field of fields) {
    lines.push(...buildFieldDocComment(field));
    const rustType = getType(field);
    const fieldType = field.isRequired ? rustType : `Option<${rustType}>`;
    lines.push(`    pub ${envKeyToRustFieldName(field.key)}: ${fieldType},`);
  }

  lines.push('}');
  return lines;
}

export function generateRustTypesSrc(fields: Array<ResolvedFieldType>): string {
  const publicFields = fields.filter((field) => !field.isSensitive);

  const src = [
    RUST_AUTOGENERATED_BANNER,
    ...formatRustStruct(
      'CoercedEnvSchema',
      'Coerced env schema (matches varlock coercion).',
      fields,
      (field) => getRustCoercedTypeString(field.coerced),
    ),
    ...formatRustStruct(
      'PublicCoercedEnvSchema',
      'Non-sensitive coerced env schema keys.',
      publicFields,
      (field) => getRustCoercedTypeString(field.coerced),
    ),
    ...formatRustStruct(
      'EnvSchemaAsStrings',
      'Raw values from std::env (always strings).',
      fields,
      (field) => getRustRawStringTypeString(field.rawString),
    ),
  ];

  return src.join('\n');
}
