import crypto from 'node:crypto';
import fs from 'node:fs';
import _ from '@env-spec/utils/my-dash';
import { getAutogeneratedBanner } from '../banners';
import {
  type CoercedType,
  type ResolvedFieldType,
} from '../shared';

function getItemTsTypeString(coerced: CoercedType): string {
  if (coerced === 'number') return 'number';
  if (coerced === 'boolean') return 'boolean';
  if (coerced === 'object') return 'Record<string, any>';
  if (typeof coerced === 'object' && 'enum' in coerced) {
    if (!coerced.enum.length) return 'never';
    return coerced.enum.map((option) => JSON.stringify(option)).join(' | ');
  }
  return 'string';
}

const ICON_SIZE = 20;

let iconCacheFolderInit = false;
const iconInMemoryCache: Record<string, string> = {};

async function fetchIconSvg(
  iconifyName: string,
  color = '808080',
  iconCacheFolder = '/tmp/varlock-icon-cache',
) {
  if (!iconCacheFolderInit) {
    fs.mkdirSync(iconCacheFolder, { recursive: true });
    iconCacheFolderInit = true;
  }

  const iconPath = `${iconCacheFolder}/${iconifyName}-${ICON_SIZE}.svg`;

  let svgSrc: string | undefined;
  if (iconInMemoryCache[iconPath]) {
    svgSrc = iconInMemoryCache[iconPath];
  } else if (fs.existsSync(iconPath)) {
    const svgFileBuffer = await fs.promises.readFile(iconPath, 'utf-8');
    svgSrc = svgFileBuffer.toString();
    iconInMemoryCache[iconPath] = svgSrc;
  } else {
    try {
      const iconSvg = await fetch(`https://api.iconify.design/${iconifyName.replace(':', '/')}.svg?height=${ICON_SIZE}`);
      svgSrc = await iconSvg.text();
    } catch {
      return;
    }
    if (!svgSrc) return;

    if (svgSrc) {
      await fs.promises.writeFile(iconPath, svgSrc, 'utf-8');
      iconInMemoryCache[iconPath] = svgSrc;
    }
  }

  const hexColor = color.startsWith('#') ? color : `#${color}`;
  const colorizedSvg = svgSrc.replaceAll('currentColor', hexColor);
  return colorizedSvg;
}

async function getTsDefinitionForField(field: ResolvedFieldType, indentLevel = 0) {
  const i = _.times(indentLevel, () => '  ').join('');
  const itemSrc = [];
  const { docs } = field;

  const jsDocLines = [];

  jsDocLines.push(`**${field.key}**${field.isSensitive ? ' 🔐 _sensitive_' : ''}`);

  if (docs.description) jsDocLines.push(...docs.description.split('\n'));

  if (docs.icon) {
    const iconSvg = await fetchIconSvg(docs.icon);
    if (iconSvg) jsDocLines.push(`![icon](data:image/svg+xml;utf-8,${encodeURIComponent(iconSvg)}) `);
  }

  if (docs.docsLinks.length) {
    jsDocLines.push('');
    docs.docsLinks.forEach((docsEntry) => {
      const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
      jsDocLines.push(`📚 {@link ${docsLink}}`);
    });
  }

  if (docs.isDeprecated) {
    jsDocLines.push('');
    jsDocLines.push(docs.deprecationMessage ? `@deprecated ${docs.deprecationMessage}` : '@deprecated');
  }

  if (jsDocLines.length === 1) {
    itemSrc.push(`/** ${jsDocLines[0]} */`);
  } else if (jsDocLines.length > 1) {
    itemSrc.push(...[
      '/**',
      ..._.flatMap(jsDocLines, (line) => [` * ${line.replace(/\*\//g, '* /')}  `]),
      ' */',
    ]);
  }

  itemSrc.push(`${field.key}${field.isRequired ? '' : '?'}: ${getItemTsTypeString(field.coerced)};`);
  itemSrc.push('');
  return _.map(itemSrc, (line) => `${i}${line}`);
}

/**
 * How the coerced `ENV` object is exposed to TypeScript:
 * - `augment` (default): globally augment `varlock/env` so `import { ENV } from 'varlock/env'` is typed.
 *   Simple, but in monorepos every in-scope package's schema merges into the one global module.
 * - `module`: emit a package-local importable `ENV` (re-exports the runtime proxy, typed to this
 *   package's schema). No global augmentation, so nothing merges across packages. Requires a
 *   `.ts`/`.js` output path (a `.d.ts` has no runtime binding).
 * - `none`: emit only the type definitions, no `ENV` binding.
 */
export type TsEnvExposure = 'augment' | 'module' | 'none';
/**
 * How a global env object (`process.env` / `import.meta.env`) is augmented:
 * - `loose`: typed defined keys but also allow arbitrary extra string keys.
 * - `strict`: only the defined keys are typed. (For `process.env`, `@types/node` already declares a
 *   base string index signature that declaration-merging can't remove, so this is best-effort.)
 * - `none`: don't augment it.
 */
export type TsGlobalAugment = 'strict' | 'loose' | 'none';
export type TsGenOptions = {
  env?: TsEnvExposure;
  processEnv?: TsGlobalAugment;
  importMetaEnv?: TsGlobalAugment;
};

// defaults preserve the historical output: augment `varlock/env`, and augment both globals with
// only the defined keys (`strict`). Note: `@types/node` gives `process.env` a base string index
// signature we can't remove, so extra keys remain allowed there regardless.
const DEFAULT_TS_GEN_OPTIONS = {
  env: 'augment',
  processEnv: 'strict',
  importMetaEnv: 'strict',
} satisfies Required<TsGenOptions>;

const TS_ENV_EXPOSURE_VALUES: ReadonlyArray<TsEnvExposure> = ['augment', 'module', 'none'];
const TS_GLOBAL_AUGMENT_VALUES: ReadonlyArray<TsGlobalAugment> = ['strict', 'loose', 'none'];

function coerceOption<T extends string>(
  raw: unknown,
  allowed: ReadonlyArray<T>,
  fallback: T,
  optionName: string,
): T {
  if (raw === undefined || raw === null) return fallback;
  if (typeof raw === 'string' && (allowed as ReadonlyArray<string>).includes(raw)) return raw as T;
  throw new Error(`@generateTsTypes - invalid \`${optionName}\` value: ${JSON.stringify(raw)}. Allowed: ${allowed.join(', ')}`);
}

/** Parse+validate raw decorator args into resolved TS generator options. */
function resolveTsGenOptions(options: Record<string, any> = {}): Required<TsGenOptions> {
  return {
    env: coerceOption(options.env, TS_ENV_EXPOSURE_VALUES, DEFAULT_TS_GEN_OPTIONS.env, 'env'),
    processEnv: coerceOption(options.processEnv, TS_GLOBAL_AUGMENT_VALUES, DEFAULT_TS_GEN_OPTIONS.processEnv, 'processEnv'),
    importMetaEnv: coerceOption(options.importMetaEnv, TS_GLOBAL_AUGMENT_VALUES, DEFAULT_TS_GEN_OPTIONS.importMetaEnv, 'importMetaEnv'),
  };
}

// `loose` explicitly allows arbitrary extra keys via an index signature; `strict` lists only the
// defined keys. Returns the interface body suffix (either empty `{}` or `{ <index sig> }`).
function augmentBody(mode: Exclude<TsGlobalAugment, 'none'>, indent: string): string {
  if (mode === 'strict') return '{}';
  return `{\n${indent}  [key: string]: string | undefined;\n${indent}}`;
}

export async function generateTsTypesSrc(fields: Array<ResolvedFieldType>, options: TsGenOptions = {}) {
  const opts = resolveTsGenOptions(options);
  const tsSrc = [
    getAutogeneratedBanner('//'),
    '// @ts-nocheck',
    '/* eslint-disable */',
  ];

  // module mode re-exports the runtime ENV proxy, so we need to import it
  if (opts.env === 'module') {
    tsSrc.push("import { ENV as _ENV } from 'varlock/env';", '');
  }

  tsSrc.push('export type CoercedEnvSchema = {');
  for (const field of fields) {
    tsSrc.push(...await getTsDefinitionForField(field, 1));
  }
  tsSrc.push('};\n');

  const schemaHash = crypto.createHash('md5')
    .update(fields.map((f) => f.key).sort().join(','))
    .digest('hex')
    .slice(0, 8);
  const schemaAlias = `_CoercedEnvSchema_${schemaHash}`;
  const stringsAlias = `_EnvSchemaAsStrings_${schemaHash}`;

  tsSrc.push(`type ${schemaAlias} = CoercedEnvSchema;`);

  const exposedNonSensitiveKeys: Array<string> = [];
  for (const field of fields) {
    if (!field.isSensitive) exposedNonSensitiveKeys.push(field.key);
  }

  // globally augment `varlock/env` so `import { ENV } from 'varlock/env'` is typed
  if (opts.env === 'augment') {
    tsSrc.push(`
declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<${schemaAlias}> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<${schemaAlias}, '${exposedNonSensitiveKeys.join("' | '")}'>> {}
}
`);
  }

  tsSrc.push(`
export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};
`);

  tsSrc.push(`type ${stringsAlias} = EnvSchemaAsStrings;`);

  // module mode: emit a package-local importable ENV typed to *this* package's schema.
  // runtime is identical (still the shared proxy from 'varlock/env'); types stay file-scoped
  // so nothing merges across packages — safe for monorepos.
  if (opts.env === 'module') {
    tsSrc.push(`
export type PublicCoercedEnvSchema = Readonly<Pick<CoercedEnvSchema, '${exposedNonSensitiveKeys.join("' | '")}'>>;

// re-export of the runtime ENV proxy, typed to this package's schema
export const ENV = _ENV as unknown as Readonly<CoercedEnvSchema>;
`);
  }

  const globalBlocks: Array<string> = [];
  if (opts.importMetaEnv !== 'none') {
    globalBlocks.push(`
  // add types for global import.meta.env
  interface ImportMetaEnv extends ${stringsAlias} ${augmentBody(opts.importMetaEnv, '  ')}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }`);
  }
  if (opts.processEnv !== 'none') {
    globalBlocks.push(`
  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends ${stringsAlias} ${augmentBody(opts.processEnv, '    ')}
  }`);
  }

  if (globalBlocks.length) {
    tsSrc.push('declare global {', ...globalBlocks, '}');
  }

  return tsSrc.join('\n');
}
