import crypto from 'node:crypto';
import fs from 'node:fs';
import _ from '@env-spec/utils/my-dash';
import type { TypeGenItemInfo } from '../../config-item';
import { getAutogeneratedBanner } from '../banners';
import {
  resolveCoercedType,
  resolveFieldType,
  type CoercedType,
} from '../shared';

function getItemTsTypeString(coerced: CoercedType): string {
  if (coerced === 'number') return 'number';
  if (coerced === 'boolean') return 'boolean';
  if (coerced === 'object') return 'Record<string, any>';
  if (typeof coerced === 'object' && 'enum' in coerced) {
    if (!coerced.enum.length) return 'never';
    return coerced.enum.map((option) => JSON.stringify(option)).join(' | ');
  }
  return 'string';
}

const ICON_SIZE = 20;

let iconCacheFolderInit = false;
const iconInMemoryCache: Record<string, string> = {};

async function fetchIconSvg(
  iconifyName: string,
  color = '808080',
  iconCacheFolder = '/tmp/varlock-icon-cache',
) {
  if (!iconCacheFolderInit) {
    fs.mkdirSync(iconCacheFolder, { recursive: true });
    iconCacheFolderInit = true;
  }

  const iconPath = `${iconCacheFolder}/${iconifyName}-${ICON_SIZE}.svg`;

  let svgSrc: string | undefined;
  if (iconInMemoryCache[iconPath]) {
    svgSrc = iconInMemoryCache[iconPath];
  } else if (fs.existsSync(iconPath)) {
    const svgFileBuffer = await fs.promises.readFile(iconPath, 'utf-8');
    svgSrc = svgFileBuffer.toString();
    iconInMemoryCache[iconPath] = svgSrc;
  } else {
    try {
      const iconSvg = await fetch(`https://api.iconify.design/${iconifyName.replace(':', '/')}.svg?height=${ICON_SIZE}`);
      svgSrc = await iconSvg.text();
    } catch {
      return;
    }
    if (!svgSrc) return;

    if (svgSrc) {
      await fs.promises.writeFile(iconPath, svgSrc, 'utf-8');
      iconInMemoryCache[iconPath] = svgSrc;
    }
  }

  const hexColor = color.startsWith('#') ? color : `#${color}`;
  const colorizedSvg = svgSrc.replaceAll('currentColor', hexColor);
  return colorizedSvg;
}

function getItemTsType(info: TypeGenItemInfo): string {
  return getItemTsTypeString(resolveCoercedType(info));
}

export async function getTsDefinitionForItem(info: TypeGenItemInfo, indentLevel = 0) {
  const i = _.times(indentLevel, () => '  ').join('');
  const itemSrc = [];

  const jsDocLines = [];

  jsDocLines.push(`**${info.key}**${info.isSensitive ? ' 🔐 _sensitive_' : ''}`);

  if (info.description) jsDocLines.push(...info.description.split('\n'));

  const iconName = info.icon;
  if (iconName) {
    const iconSvg = await fetchIconSvg(iconName);
    if (iconSvg) jsDocLines.push(`![icon](data:image/svg+xml;utf-8,${encodeURIComponent(iconSvg)}) `);
  }

  const docsLinks = info.docsLinks;
  if (docsLinks.length) {
    jsDocLines.push('');
    docsLinks.forEach((docsEntry) => {
      const docsLink = _.compact([docsEntry.url, docsEntry.description]).join(' | ');
      jsDocLines.push(`📚 {@link ${docsLink}}`);
    });
  }

  if (info.isDeprecated) {
    jsDocLines.push('');
    jsDocLines.push(info.deprecationMessage ? `@deprecated ${info.deprecationMessage}` : '@deprecated');
  }

  if (jsDocLines.length === 1) {
    itemSrc.push(`/** ${jsDocLines[0]} */`);
  } else if (jsDocLines.length > 1) {
    itemSrc.push(...[
      '/**',
      ..._.flatMap(jsDocLines, (line) => [` * ${line.replace(/\*\//g, '* /')}  `]),
      ' */',
    ]);
  }

  const itemTsType = getItemTsType(info);
  const isRequired = info.isRequired && !info.isRequiredDynamic;
  itemSrc.push(`${info.key}${isRequired ? '' : '?'}: ${itemTsType};`);
  itemSrc.push('');
  return _.map(itemSrc, (line) => `${i}${line}`);
}

export async function generateTsTypesSrc(items: Array<TypeGenItemInfo>) {
  const fields = items.map(resolveFieldType);
  const tsSrc = [
    getAutogeneratedBanner('//'),
    '// @ts-nocheck',
    '/* eslint-disable */',
    'export type CoercedEnvSchema = {',
  ];

  for (const info of items) {
    tsSrc.push(...await getTsDefinitionForItem(info, 1));
  }

  tsSrc.push('};\n');

  const schemaHash = crypto.createHash('md5')
    .update(items.map((i) => i.key).sort().join(','))
    .digest('hex')
    .slice(0, 8);
  const schemaAlias = `_CoercedEnvSchema_${schemaHash}`;
  const stringsAlias = `_EnvSchemaAsStrings_${schemaHash}`;

  tsSrc.push(`type ${schemaAlias} = CoercedEnvSchema;`);

  const exposedNonSensitiveKeys: Array<string> = [];
  for (const field of fields) {
    if (!field.isSensitive) exposedNonSensitiveKeys.push(field.key);
  }

  tsSrc.push(`
declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<${schemaAlias}> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<${schemaAlias}, '${exposedNonSensitiveKeys.join("' | '")}'>> {}
}
`);

  tsSrc.push(`
export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};
`);

  tsSrc.push(`type ${stringsAlias} = EnvSchemaAsStrings;`);

  const importMetaEnvTypes = true;
  const processEnvTypes = true;

  const IMPORT_META_AUGMENTATION = `
  // add types for global import.meta.env
  interface ImportMetaEnv extends ${stringsAlias} {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }`;
  const PROCESS_ENV_AUGMENTATION = `
  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends ${stringsAlias} {}
  }`;

  tsSrc.push(...[
    'declare global {',
    importMetaEnvTypes && IMPORT_META_AUGMENTATION,
    processEnvTypes && PROCESS_ENV_AUGMENTATION,
    '}',
  ].filter(Boolean));

  return tsSrc.join('\n');
}
