name: Release varlock CLI binaries

# normal CI release workflow handles publishing multiple packages from the monorepo
# this workflow triggered by a release `varlock@x.y.z`
on:
  release:
    types: [published]
    tags:
      - varlock@*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # if: startsWith(github.ref, 'refs/tags/varlock@') && contains(github.ref, '.')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'pnpm'
      - name: Install node deps
        run: pnpm i
      - name: Enable turborepo build cache
        uses: rharkor/caching-for-turbo@v1.8
      # ------------------------------------------------------------

      - name: get version from release tag
        run: |
          # get the full release tag name - ex: varlock@1.2.3
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          # get the version only from the tag - ex: 1.2.3
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/varlock@}" >> $GITHUB_ENV

      # necessary to bundle macos binaries from linux machine
      - name: install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - name: build SEA dist files (CJS, no deps)
        run: pnpm run --filter varlock build:sea

      - name: pkg binaries
        run: node scripts/build-binaries.js
      
      - name: add binaries to GH release
        run: gh release upload ${{ env.RELEASE_TAG }} packages/varlock/dist-sea/*.{tar.gz,zip}

      - name: Add release checksums
        uses: wangzuo/action-release-checksums@v1
    
      # UPDATE HOMEBREW FORMULA --- 
      - name: checkout homebrew tap repo
        uses: actions/checkout@v4
        with:
          repository: "dmno-dev/homebrew-tap"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: 'update formula'
        run: node scripts/update-homebrew-formula.js ${{ env.RELEASE_VERSION }}
      - name: commit and push homebrew tap
        run: |
          cd homebrew-tap
          git config --global user.name 'theoephraim'
          git config --global user.email 'theo@dmno.dev'
          git add .
          git commit -m "${{ env.RELEASE_VERSION }}"
          git tag "${{ env.RELEASE_VERSION }}"
          git push origin HEAD --tags