# inspired by https://github.com/systeminit/si/blob/main/.github/workflows/community-check.yml

name: Label community PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    steps:
      - name: Label PR based on maintainer status
        uses: actions/github-script@v8
        with:
          script: |
            const MAINTAINERS = 'theoephraim philmillman'.split(' ');
            const pr = context.payload.pull_request;
            const isRelease = pr.head.ref === 'changeset-release/main';
            const isRenovate = pr.user.login === 'renovate[bot]';
            const isCopilot = pr.user.login === 'Copilot';
            const isMaintainer = MAINTAINERS.includes(pr.user.login);
            let label = 'community';
            if (isRelease) label = 'release';
            else if (isRenovate) label = 'bot';
            else if (isMaintainer || isCopilot) label = 'maintainer';
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            });
      - name: Label PR based on changed files
        uses: actions/labeler@v6
        with:
          configuration-path: .github/config/labeler.yaml
