name: Release _preview_ packages
on:
  pull_request:
  push:
    branches-ignore:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          # by default only the current commit is fetched
          # but we need more history to be able to compare to main
          # TODO: ideally we would just fetch the history between origin/main and the current commit
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
      - name: Install node deps
        run: bun install
      - name: Enable turborepo build cache
        uses: rharkor/caching-for-turbo@v2.3.13

      # ------------------------------------------------------------
      - name: Build publishable npm packages
        run: bun run build:libs
        env:
          BUILD_TYPE: preview
      # we use a custom script to run `npx pkg-pr-new publish`
      # so that we can determine which packages to release
      - name: Release preview packages
        run: bun run scripts/release-preview.ts
